language: node_js
node_js: '12.18.4'
cache:
  npm: true
  directories:
    - ~/.cache
env:
  - PORT=8000 NEXT_PUBLIC_API_HOST=https://devapi.adsabs.harvard.edu/v1 HOST=http://localhost:8000
git:
  submodules: false
install:
  - yarn install
  - yarn cypress install
script:
  - yarn test:ci
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./.travis/run_on_pull_requests; fi'
