language: node_js
node_js: '12.18.4'
cache:
  directories:
    - ~/.npm
    - ~/.cache
git:
  submodules: false
install: yarn install
script:
  - yarn test
  - yarn dev &
  - yarn cy
  - kill $(jobs -p) || true
