language: node_js
node_js: '12.18.4'
cache:
  npm: true
  directories:
    - ~/.cache
git:
  submodules: false
install:
  - yarn install
  - yarn cypress install
script:
  - yarn test:ci
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./.travis/run_on_pull_requests; fi'
