codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch: false

  range: 40..60
  round: up
  precision: 1

ignore:
  - src/**/*.test.*
  - src/mocks/**/*
  - e2e/**/*
  - .*/**/*

comment:
  layout: diff, files
  require_changes: true
  behavior: default

github_checks:
  annotations: false
