services:

  # Run build server
  dev:
    env_file: .env.local
    ports:
      - '8000:8000'
    build:
      context: .
      target: dev
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    user: ${USER_UID:-1000}:${USER_GID:-1000}
    volumes:
      - .:/app

  # Run production server
  prod:
    env_file: .env.local
    ports:
      - '8000:8000'
    tty: true
    build:
      context: .
      target: prod
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    user: ${USER_UID:-1000}:${USER_GID:-1000}
    networks:
      - internal

  # Run unit tests
  unit:
    env_file: .env.local
    build:
      context: .
      target: unit
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    user: ${USER_UID:-1000}:${USER_GID:-1000}
    tty: true
    volumes:
      - ./src:/app/src

  # Run e2e tests on production build
  e2e:
    env_file: .env.local
    init: true
    ipc: host
    build:
      context: .
      target: e2e
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    user: ${USER_UID:-1000}:${USER_GID:-1000}
    tty: true
    depends_on:
      - prod
    volumes:
      - ./playwright.config.ts:/app/playwright.config.ts
      - ./.playwright:/app/.playwright
      - ./e2e:/app/e2e
      - ./test-results:/app/test-results
    networks:
      - internal

  # Runs UI web server
  e2e-ui:
    env_file: .env.local
    init: true
    ipc: host
    cap_add:
      - SYS_ADMIN
    build:
      context: .
      target: e2e
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    user: ${USER_UID:-1000}:${USER_GID:-1000}
    tty: true
    ports:
      - '3000:3000'
    depends_on:
      - prod
    volumes:
      - ./e2e:/app/e2e
      - ./.playwright:/app/.playwright
      - ./playwright.config.ts:/app/playwright.config.ts
    command: [ "test", "--ui", "--ui-host=0.0.0.0", "--ui-port=3000" ]
    networks:
      - internal

networks:
  internal:
    driver: bridge
