import {
  NasaIcon,
  SpaceTelescopeIcon,
  KeplerIcon,
  JwstIcon,
  DomeIcon,
  TwinDomeIcon,
  RadioDishIcon,
  DishArrayIcon,
  SetiIcon,
  SolarIcon,
  StereoIcon,
  XrayIcon,
  BookIcon,
  AtomIcon,
  ClockIcon,
  StarClusterIcon,
  CatalogIcon,
  DocIcon,
  VintageScopeIcon,
  StarOrbitIcon,
  OldSatelliteIcon,
  UsgsIcon,
} from '../icons/browser/bibgroup';

import { IFacetDetail } from './types';

export const bibgroupDetails: Record<string, IFacetDetail> = {
  PhysEd: { facetKey: 'PhysEd', title: 'Physics Education', icon: AtomIcon },
  USGS: {
    facetKey: 'USGS',
    title: 'U.S. Geological Survey',
    icon: UsgsIcon,
    desc: 'Publications authored by USGS scientists over the entire century-plus history of the bureau — journal articles, series reports, book chapters, and other government publications. Maintained by ADS, sourced from the USGS Publications Warehouse.',
  },
  NTRS: { facetKey: 'NTRS', title: 'NASA Technical Reports Server', icon: NasaIcon },
  'NASA SLSL': { facetKey: 'NASA SLSL', title: 'NASA Space Life Sciences Library', icon: NasaIcon },
  CfA: { facetKey: 'CfA', title: 'Center for Astrophysics', icon: StarOrbitIcon },
  'Historical Literature': {
    facetKey: 'Historical Literature',
    title: 'Historical Astronomy Literature',
    icon: BookIcon,
  },
  'NASA PubSpace': {
    facetKey: 'NASA PubSpace',
    title: 'NASA PubSpace',
    icon: NasaIcon,
    desc: "Publications made available via NASA's designated public access repository, PubSpace — NASA-funded scholarly publications, primarily accepted manuscripts and peer-reviewed publisher versions of record. Maintained by ADS, sourced from the NASA STI Repository (NTRS) collections.",
  },
  Spitzer: { facetKey: 'Spitzer', title: 'Spitzer Space Telescope', icon: SpaceTelescopeIcon },
  NRAO: { facetKey: 'NRAO', title: 'National Radio Astronomy Observatory', icon: RadioDishIcon },
  HST: {
    facetKey: 'HST',
    title: 'Hubble Space Telescope',
    icon: SpaceTelescopeIcon,
    desc: 'Refereed articles that made scientific use of data from the NASA/ESA Hubble Space Telescope since 1991, available from the Mikulski Archive for Space Telescopes (MAST) at STScI. Papers are added continuously and may lag up to one year from publication.',
  },
  'ESO/Telescopes': {
    facetKey: 'ESO/Telescopes',
    title: 'European Southern Observatory (ESO) Telescope Publications',
    icon: DomeIcon,
    desc: 'Refereed articles using data from ESO telescopes. Papers since 1996 using Paranal or Chajnantor facilities (and La Silla since 2000) reference program IDs and link to data in the ESO Science Archive. Maintained by the ESO Library, updated daily.',
  },
  Chandra: {
    facetKey: 'Chandra',
    title: 'Chandra X-ray Observatory',
    icon: XrayIcon,
    desc: 'Articles where Chandra data contributes significantly to the science (Chandra Science Papers), linked to the data in the Chandra Data Archive on which they are based. Maintained by the Chandra Data Archive.',
  },
  NOIRLab: {
    facetKey: 'NOIRLab',
    title: 'NSF NOIRLab',
    icon: DomeIcon,
    desc: 'Curated list of refereed science data publications using NSF NOIRLab telescope data and data products & services — International Gemini Observatory, NOIRLab MSO telescopes, Blanco, SOAR, and others. Updated weekly.',
  },
  'Leiden Observatory': {
    facetKey: 'Leiden Observatory',
    title: 'Leiden Observatory',
    icon: VintageScopeIcon,
  },
  'Solar Dynamics Observatory': {
    facetKey: 'Solar Dynamics Observatory',
    title: 'Solar Dynamics Observatory',
    icon: SolarIcon,
    desc: "ADS library of publications and abstracts involving data from NASA's Solar Dynamics Observatory (SDO) mission or describing the mission and its instrumentation, 2000 to the present. Maintained by the SDO Project Team, updated monthly.",
  },
  XMM: { facetKey: 'XMM', title: 'XMM-Newton Observatory', icon: XrayIcon },
  NOAO: {
    facetKey: 'NOAO',
    title: 'National Optical Astronomy Observatory',
    icon: DomeIcon,
    desc: 'Curated list of NOAO publications from 1990 to October 2019, when NOAO became part of NSF NOIRLab. Refereed science data publications using NOAO telescope data and data products & services; citations are also included in the NOIRLab bibgroup.',
  },
  SOHO: {
    facetKey: 'SOHO',
    title: 'Solar & Heliospheric Observatory',
    icon: SolarIcon,
    desc: 'ADS library of refereed publications for the ESA/NASA SOHO mission, starting in 1995. Maintained by the acting ESA SOHO Project Scientist, updated every two months.',
  },
  Keck: { facetKey: 'Keck', title: 'W. M. Keck Observatory', icon: TwinDomeIcon },
  IUE: {
    facetKey: 'IUE',
    title: 'International Ultraviolet Explorer',
    icon: SpaceTelescopeIcon,
    desc: 'Refereed articles that made scientific use of data from the mission, available from the Mikulski Archive for Space Telescopes (MAST) at STScI. Papers are added continuously and may lag up to one year from publication.',
  },
  USNO: { facetKey: 'USNO', title: 'U.S. Naval Observatory', icon: ClockIcon },
  CFHT: {
    facetKey: 'CFHT',
    title: 'Canada-France-Hawaiʻi Telescope',
    icon: DomeIcon,
    desc: 'Peer reviewed papers by researchers worldwide using data from the Canada-France-Hawaiʻi Telescope, covering every instrument ever used at CFHT since 1979, plus archival and catalog papers.',
  },
  ALMA: { facetKey: 'ALMA', title: 'Atacama Large Millimeter/submillimeter Array', icon: DishArrayIcon },
  'NASA Astrobiology': { facetKey: 'NASA Astrobiology', title: 'NASA Astrobiology Program', icon: NasaIcon },
  Gemini: {
    facetKey: 'Gemini',
    title: 'International Gemini Observatory',
    icon: TwinDomeIcon,
    desc: 'Refereed articles based on observations (including observatory archive) made at the International Gemini Observatory, NSF NOIRLab, from 2000 to present. Updated monthly.',
  },
  SETI: {
    facetKey: 'SETI',
    title: 'Search for Extraterrestrial Intelligence',
    icon: SetiIcon,
    desc: 'Topical bibliographic group tracking the SETI literature — technosignature searches, theoretical explorations of technological alien life, and social aspects such as METI and post-detection protocols. Continuously maintained as part of a project at the Penn State Extraterrestrial Intelligence Center.',
  },
  Herschel: { facetKey: 'Herschel', title: 'Herschel Space Observatory', icon: SpaceTelescopeIcon },
  GALEX: {
    facetKey: 'GALEX',
    title: 'Galaxy Evolution Explorer',
    icon: SpaceTelescopeIcon,
    desc: 'Refereed articles that made scientific use of data from the mission, available from the Mikulski Archive for Space Telescopes (MAST) at STScI. Papers are added continuously and may lag up to one year from publication.',
  },
  HCOWAC: {
    facetKey: 'HCOWAC',
    title: 'Harvard Women Astronomical Computers',
    icon: VintageScopeIcon,
    desc: 'Developmental bibgroup highlighting the scientific contributions of the Women Astronomical Computers working at Harvard College Observatory by identifying their scholarly work.',
  },
  JWST: {
    facetKey: 'JWST',
    title: 'James Webb Space Telescope',
    icon: JwstIcon,
    desc: 'Refereed articles that made scientific use of data from the NASA/ESA/CSA James Webb Space Telescope since 2022, available from the Mikulski Archive for Space Telescopes (MAST) at STScI. Papers are added continuously and may lag up to one year from publication.',
  },
  WHT: {
    facetKey: 'WHT',
    title: 'William Herschel Telescope',
    icon: DomeIcon,
    desc: 'Refereed papers published since 1988 using William Herschel Telescope data. Maintained by the Isaac Newton Group of Telescopes (ING), updated yearly.',
  },
  STEREO: {
    facetKey: 'STEREO',
    title: 'Solar Terrestrial Relations Observatory',
    icon: StereoIcon,
    desc: "ADS library of refereed publications using data from NASA's STEREO mission or describing the mission and its instrumentation, 2002 to the present. Maintained by the STEREO Project Scientist, updated about once a year.",
  },
  JCMT: { facetKey: 'JCMT', title: 'James Clerk Maxwell Telescope', icon: RadioDishIcon },
  INT: {
    facetKey: 'INT',
    title: 'Isaac Newton Telescope',
    icon: DomeIcon,
    desc: 'Refereed papers published since 1984 using Isaac Newton Telescope data. Maintained by the Isaac Newton Group of Telescopes (ING), updated yearly.',
  },
  IRTF: { facetKey: 'IRTF', title: 'NASA Infrared Telescope Facility', icon: NasaIcon },
  Subaru: { facetKey: 'Subaru', title: 'Subaru Telescope', icon: StarClusterIcon },
  Kepler: {
    facetKey: 'Kepler',
    title: 'Kepler Space Telescope',
    icon: KeplerIcon,
    desc: 'Refereed articles that made scientific use of data from the mission, available from the Mikulski Archive for Space Telescopes (MAST) at STScI. Papers are added continuously and may lag up to one year from publication.',
  },
  Swift: { facetKey: 'Swift', title: 'Neil Gehrels Swift Observatory', icon: XrayIcon },
  'Pan-STARRS': {
    facetKey: 'Pan-STARRS',
    title: 'Pan-STARRS Survey',
    icon: DomeIcon,
    desc: 'Refereed articles that made scientific use of data from the Pan-STARRS PS1 survey (2012–2015), available from the Mikulski Archive for Space Telescopes (MAST) at STScI. Papers are added continuously but may lag up to one year from publication.',
  },
  TESS: {
    facetKey: 'TESS',
    title: 'Transiting Exoplanet Survey Satellite',
    icon: KeplerIcon,
    desc: 'Refereed articles that made scientific use of data from the mission, available from the Mikulski Archive for Space Telescopes (MAST) at STScI. Papers are added continuously and may lag up to one year from publication.',
  },
  GTC: { facetKey: 'GTC', title: 'Gran Telescopio Canarias', icon: DomeIcon },
  SMA: { facetKey: 'SMA', title: 'Submillimeter Array', icon: DishArrayIcon },
  FUSE: {
    facetKey: 'FUSE',
    title: 'Far Ultraviolet Spectroscopic Explorer',
    icon: SpaceTelescopeIcon,
    desc: 'Refereed articles that made scientific use of data from the mission, available from the Mikulski Archive for Space Telescopes (MAST) at STScI. Papers are added continuously and may lag up to one year from publication.',
  },
  K2: {
    facetKey: 'K2',
    title: 'K2 Mission',
    icon: KeplerIcon,
    desc: 'Refereed articles that made scientific use of data from the mission, available from the Mikulski Archive for Space Telescopes (MAST) at STScI. Papers are added continuously and may lag up to one year from publication.',
  },
  'Chandra/Technical': {
    facetKey: 'Chandra/Technical',
    title: 'Chandra Technical Papers',
    icon: DocIcon,
    desc: 'Articles pertaining to the Chandra mission, including Chandra instruments, software, and operations. Maintained by the Chandra Data Archive.',
  },
  EUVE: {
    facetKey: 'EUVE',
    title: 'Extreme Ultraviolet Explorer',
    icon: SpaceTelescopeIcon,
    desc: 'Refereed articles that made scientific use of data from the mission, available from the Mikulski Archive for Space Telescopes (MAST) at STScI. Papers are added continuously and may lag up to one year from publication.',
  },
  'Chandra/CSC': {
    facetKey: 'Chandra/CSC',
    title: 'Chandra Source Catalog',
    icon: CatalogIcon,
    desc: 'Refereed and non-refereed articles published from 2009–present related to the Chandra Source Catalog, including papers performing scientific analysis on catalog data. Updated monthly.',
  },
  Copernicus: {
    facetKey: 'Copernicus',
    title: 'Copernicus Satellite',
    icon: OldSatelliteIcon,
    desc: 'Refereed articles that made scientific use of data from the mission, available from the Mikulski Archive for Space Telescopes (MAST) at STScI. Papers are added continuously and may lag up to one year from publication.',
  },
};
