import {
  NasaIcon,
  SpaceTelescopeIcon,
  KeplerIcon,
  JwstIcon,
  DomeIcon,
  TwinDomeIcon,
  RadioDishIcon,
  DishArrayIcon,
  SetiIcon,
  SolarIcon,
  StereoIcon,
  XrayIcon,
  BookIcon,
  AtomIcon,
  ClockIcon,
  ShieldIcon,
  StarClusterIcon,
  CatalogIcon,
  DocIcon,
  VintageScopeIcon,
  StarOrbitIcon,
  OldSatelliteIcon,
} from '../icons/browser/bibgroup';

import { IFacetDescription } from './types';

export const bibgroupDescriptions: Record<string, IFacetDescription> = {
  PhysEd: { facetKey: 'PhysEd', desc: 'Physics Education', icon: AtomIcon },
  USGS: { facetKey: 'USGS', desc: 'U.S. Geological Survey', icon: ShieldIcon },
  NTRS: { facetKey: 'NTRS', desc: 'NASA Technical Reports Server', icon: NasaIcon },
  'NASA SLSL': { facetKey: 'NASA SLSL', desc: 'NASA Space Life Sciences Library', icon: NasaIcon },
  CfA: { facetKey: 'CfA', desc: 'Center for Astrophysics', icon: StarOrbitIcon },
  'Historical Literature': {
    facetKey: 'Historical Literature',
    desc: 'Historical Astronomy Literature',
    icon: BookIcon,
  },
  'NASA PubSpace': { facetKey: 'NASA PubSpace', desc: 'NASA PubSpace', icon: NasaIcon },
  Spitzer: { facetKey: 'Spitzer', desc: 'Spitzer Space Telescope', icon: SpaceTelescopeIcon },
  NRAO: { facetKey: 'NRAO', desc: 'National Radio Astronomy Observatory', icon: RadioDishIcon },
  HST: { facetKey: 'HST', desc: 'Hubble Space Telescope', icon: SpaceTelescopeIcon },
  'ESO/Telescopes': {
    facetKey: 'ESO/Telescopes',
    desc: 'European Southern Observatory (ESO) Telescope Publications',
    icon: DomeIcon,
  },
  Chandra: { facetKey: 'Chandra', desc: 'Chandra X-ray Observatory', icon: XrayIcon },
  NOIRLab: { facetKey: 'NOIRLab', desc: 'NSF NOIRLab', icon: DomeIcon },
  'Leiden Observatory': { facetKey: 'Leiden Observatory', desc: 'Leiden Observatory', icon: VintageScopeIcon },
  'Solar Dynamics Observatory': {
    facetKey: 'Solar Dynamics Observatory',
    desc: 'Solar Dynamics Observatory',
    icon: SolarIcon,
  },
  XMM: { facetKey: 'XMM', desc: 'XMM-Newton Observatory', icon: XrayIcon },
  NOAO: { facetKey: 'NOAO', desc: 'National Optical Astronomy Observatory', icon: DomeIcon },
  SOHO: { facetKey: 'SOHO', desc: 'Solar & Heliospheric Observatory', icon: SolarIcon },
  Keck: { facetKey: 'Keck', desc: 'W. M. Keck Observatory', icon: TwinDomeIcon },
  IUE: { facetKey: 'IUE', desc: 'International Ultraviolet Explorer', icon: SpaceTelescopeIcon },
  USNO: { facetKey: 'USNO', desc: 'U.S. Naval Observatory', icon: ClockIcon },
  CFHT: { facetKey: 'CFHT', desc: 'Canada-France-Hawaiʻi Telescope', icon: DomeIcon },
  ALMA: { facetKey: 'ALMA', desc: 'Atacama Large Millimeter/submillimeter Array', icon: DishArrayIcon },
  'NASA Astrobiology': { facetKey: 'NASA Astrobiology', desc: 'NASA Astrobiology Program', icon: NasaIcon },
  Gemini: { facetKey: 'Gemini', desc: 'International Gemini Observatory', icon: TwinDomeIcon },
  SETI: { facetKey: 'SETI', desc: 'Search for Extraterrestrial Intelligence', icon: SetiIcon },
  Herschel: { facetKey: 'Herschel', desc: 'Herschel Space Observatory', icon: SpaceTelescopeIcon },
  GALEX: { facetKey: 'GALEX', desc: 'Galaxy Evolution Explorer', icon: SpaceTelescopeIcon },
  HCOWAC: { facetKey: 'HCOWAC', desc: 'Harvard Women Astronomical Computers', icon: VintageScopeIcon },
  JWST: { facetKey: 'JWST', desc: 'James Webb Space Telescope', icon: JwstIcon },
  WHT: { facetKey: 'WHT', desc: 'William Herschel Telescope', icon: DomeIcon },
  STEREO: { facetKey: 'STEREO', desc: 'Solar Terrestrial Relations Observatory', icon: StereoIcon },
  JCMT: { facetKey: 'JCMT', desc: 'James Clerk Maxwell Telescope', icon: RadioDishIcon },
  INT: { facetKey: 'INT', desc: 'Isaac Newton Telescope', icon: DomeIcon },
  IRTF: { facetKey: 'IRTF', desc: 'NASA Infrared Telescope Facility', icon: NasaIcon },
  Subaru: { facetKey: 'Subaru', desc: 'Subaru Telescope', icon: StarClusterIcon },
  Kepler: { facetKey: 'Kepler', desc: 'Kepler Space Telescope', icon: KeplerIcon },
  Swift: { facetKey: 'Swift', desc: 'Neil Gehrels Swift Observatory', icon: XrayIcon },
  'Pan-STARRS': { facetKey: 'Pan-STARRS', desc: 'Pan-STARRS Survey', icon: DomeIcon },
  TESS: { facetKey: 'TESS', desc: 'Transiting Exoplanet Survey Satellite', icon: KeplerIcon },
  GTC: { facetKey: 'GTC', desc: 'Gran Telescopio Canarias', icon: DomeIcon },
  SMA: { facetKey: 'SMA', desc: 'Submillimeter Array', icon: DishArrayIcon },
  FUSE: { facetKey: 'FUSE', desc: 'Far Ultraviolet Spectroscopic Explorer', icon: SpaceTelescopeIcon },
  K2: { facetKey: 'K2', desc: 'K2 Mission', icon: KeplerIcon },
  'Chandra/Technical': { facetKey: 'Chandra/Technical', desc: 'Chandra Technical Papers', icon: DocIcon },
  EUVE: { facetKey: 'EUVE', desc: 'Extreme Ultraviolet Explorer', icon: SpaceTelescopeIcon },
  'Chandra/CSC': { facetKey: 'Chandra/CSC', desc: 'Chandra Source Catalog', icon: CatalogIcon },
  Copernicus: { facetKey: 'Copernicus', desc: 'Copernicus Satellite', icon: OldSatelliteIcon },
};
