import { IExplorerFacet, IExplorerCollection } from './types';
import { DatasetIcon, EPrintIcon, JournalArticleIcon, SoftwareIcon } from '../icons/browser/doctype';
import { AstroDataIcon, ClimateIcon } from '../icons/browser/data';
import { JwstIcon, NasaIcon, SetiIcon, UsgsIcon } from '../icons/browser/bibgroup';

const selectDataFacetKeys = [
  'SIMBAD',
  'MAST',
  'TNS',
  'IRSA',
  'CDS',
  'ESA',
  'HEASARC',
  'ESO',
  'Chandra',
  'XMM',
  'NED',
  'ORNL.DAAC',
  'NOAA',
  'vizier',
  'ALMA',
  'KOA',
  'PDS',
  'GSFC',
  'Gemini',
  'Herschel',
  'USGS',
  'CopernicusEU',
  'NOAO',
  'GCPD',
  'Spitzer',
  'GESDISC.DAAC',
  'INES',
  'NASA.SPDF',
  'ATNF',
  'ASDC.DAAC',
  'ECMWF',
  'Astromat',
  'LLNL',
  'ISO',
  'PO.DAAC',
  'JOSS',
  'sedac',
  'NSIDC.DAAC',
  'NExScI',
  'NASA',
  'ARI',
  'MetOffice',
  'UCAR',
  'OB.DAAC',
  'LP.DAAC',
  'Dryad',
  'PANGAEA',
  'StarGlass',
  'HDRL',
  'part of Copernicus',
  'Google',
  'ColoState',
  'DRYAD',
  'GHRC.DAAC',
  'NCAR',
  'CMDN',
  'IRIS',
  'ipac',
  'LAADS.DAAC',
  'NSIDC',
  'UCSD',
  'IBVS',
  'CEDA',
  'GTC',
  'GFZ',
  'SEDAC.DAAC',
  'UEA',
  'UHI',
  'LaRC',
  'EMAC',
  'TPDC',
  'FDSN',
  'THEMIS',
  'NERC',
  'OPENMADRIGAL',
  'AVISO',
  'BoM',
  '4TU.ResearchData',
  'DKRZ',
  'Uiowa',
  'ColoradoState',
  'EarthChem',
  'UNAVCO',
  'Hydroshare',
  'JAXA',
  'NagoyaU',
  'RSS',
  'PIK',
  'Generic-Mapping-Tools',
  'NCEI',
  'ETHZ',
  'IMD Pune',
  'GLEAM',
  'JHUAPL',
  'JAMSTEC',
  'HYCOM',
  'WHOI',
  'ArcticData',
  'CDDIS.DAAC',
  'Eurostat',
  'MIT',
  'ColumbiaUni',
  'LBL',
  'IFREMER',
  'ASU',
  'JRA-55',
  'FLUXNET',
  'NGL',
  'CCDC',
  'BCO-DMO',
  'UCBerkeley',
  'DIAS',
  'INGV',
  'SEDAC',
  'UCF',
  'UMD',
  'BerkeleyEarth',
  'SABER',
  'UMassLowell',
  'ARM',
  'STSCI',
  'UCSB',
  'Copernicus',
  'EarthRef',
  'GAVO',
  'INTERMAGNET',
  'LMD',
  'CCRC',
  'ChinaVO',
  'IAP',
  'IPSL',
  'TDR',
  'DeepBlue',
  'WISC',
  'KNMI',
  'CEDC',
  'MeridianProject',
  'OceanOPS',
  'CIG',
  'GRAS',
  'Stanford',
  'ORFEUS',
  'BNU',
  'GeoNet',
  'UniTokyo',
  'INCOIS',
  'UniCalgary',
  'JPL',
  'Canada',
  'UNH',
  'UniHamburg',
  'BGS',
  'REMSS',
  'METNorway',
  'IEDA',
  'GNSSWHU',
  'CSTR',
  'IRI',
  'ASF.DAAC',
  'GNSS',
  'UniBe',
  'CALTECH',
  'HirosakiUni',
  'CSIC',
  'BfG',
  'CN-ARGO',
  'UCLA',
  'UW',
  'BCC-CMA',
  'GMU',
  'Harvard',
  'ISGI',
  'GHDx',
  'JASMIN',
  'NILU',
  'CDPP',
  'UMT',
  'AcA',
  'Dataverse',
  'India-WRIS',
  'GBIF',
  'Inkscape',
  'MPG',
  'MagIC',
  'ACRI',
  'Earthbyte',
  'UCI',
  'UniHawaii',
  'AmeriFlux',
  'CARISMA',
  'IllinoisDataBank',
  'KyotoU',
  'UNB',
  'WUSTL',
  'DTU',
  'FluxCom',
  'GlobalDamWatch',
  'Rutgers',
  'TexasA&M',
  'UCoBoulder',
  'equake-rc',
  'Geochron',
  'EUREF',
  'Oulu',
  'StockholmUni',
  'TUGraz',
  'TsinghuaUni',
  'NBSC',
  'NIES',
  'TAMUCC',
  'UMICH',
  'UMN',
  'GATS',
  'GeoHK',
  'USDOE',
  'EIDA INGV',
  'NSO',
  'OpenEI',
  'SPBU-RU',
  'AMISR',
  'IBGE',
  'NWRA',
  'source',
  'ASDC-ASIM',
  'UniArizona',
  'UniLeicester',
  'BGI',
  'GlobColour',
  'ICTP',
  'Astroverse',
  'Geant4',
  'SONEL',
  'UniChile',
  'NCI',
  'NRCan',
  'SCSIO',
  'UniUtah',
  'NASA.GeneLab',
  'GPlates',
  'NSMC',
  'UniTehran',
  'INPE',
  'ParisObs',
  'SRI International',
  'SentinelHub',
  'ASTRON',
  'CLWeb',
  'Formosat',
  'GWDG',
  'IGN',
  'IZMIRAN',
  'LASG',
  'NIST',
  'NLLOC',
  'SESAR',
  'SNU',
  'protocols',
  'GESLA',
  'GSI',
  'USGODAE',
  'UniWashington',
  'WRMC-BSRN',
  'AAS',
  'Berkeley',
  'CASEarth',
  'CDEC',
  'EIDA NOA',
  'EUDP',
  'Meereisportal',
  'PKU',
  'UniKansas',
  'AFREF',
  'EIDA GFZ',
  'GeoROC',
  'NII',
  'PDC',
  'AVISO-CNES',
  'AusPass',
  'ERDC',
  'GOTM',
  'GOV.UK',
  'PSU',
  'SWRI',
  'eartH2Observe',
];

export const explorerCollections: Record<IExplorerCollection['id'], IExplorerCollection> = {
  database: {
    id: 'database',
    facetField: 'database',
    label: 'Discipline',
    searchQueryField: 'database',
    facetSearchParams: { field: 'database', level: 'root' },
  },
  doctype: {
    id: 'doctype',
    facetField: 'doctype_facet_hier',
    label: 'Record Type',
    searchQueryField: 'doctype',
    image: '/images/browse/doctype.jpg',
    facetSearchParams: { field: 'doctype_facet_hier', level: 'child' },
    ignoreFacetKeys: ['0/Article', '0/Non-Article'],
  },
  bibgroup: {
    id: 'bibgroup',
    facetField: 'bibgroup_facet',
    label: 'Curated Bibliography',
    searchQueryField: 'bibgroup',
    image: '/images/browse/bibgroup.jpg',
    facetSearchParams: { field: 'bibgroup_facet', level: 'root' },
  },
  data: {
    id: 'data',
    facetField: 'data_facet',
    label: 'Records linked to scientific archives',
    searchQueryField: 'data',
    image: '/images/browse/datacollection.jpg',
    facetSearchParams: { field: 'data_facet', level: 'root' },
    filterFacetKeys: selectDataFacetKeys,
  },
};

export const databases: Record<IExplorerCollection['id'], IExplorerFacet> = {
  astronomy: {
    id: 'astronomy',
    facetKey: 'astronomy',
    searchQueryValue: 'astronomy',
    label: 'Astronomy',
    image: '/images/browse/discipline/astronomy.jpg',
    subset: ['astrophysics', 'heliophysics', 'planetary'],
  },
  physics: {
    id: 'physics',
    facetKey: 'physics',
    searchQueryValue: 'physics',
    label: 'Physics',
    image: '/images/browse/discipline/physics.jpg',
    subset: [],
  },
  earthscience: {
    id: 'earthscience',
    facetKey: 'earthscience',
    searchQueryValue: 'earthscience',
    label: 'Earth Science',
    image: '/images/browse/discipline/earth-science.jpg',
    subset: [],
  },
  general: {
    id: 'general',
    facetKey: 'general',
    searchQueryValue: 'general',
    label: 'General Science',
    image: '/images/browse/discipline/general-science.jpg',
    subset: [],
  },
  astrophysics: {
    id: 'astrophysics',
    facetKey: 'astrophysics',
    searchQueryValue: 'astrophysics',
    label: 'Astrophysics',
    image: '/images/browse/discipline/astrophysics.jpg',
    subset: [],
  },
  heliophysics: {
    id: 'heliophysics',
    facetKey: 'heliophysics',
    searchQueryValue: 'heliophysics',
    label: 'Heliophysics',
    image: '/images/browse/discipline/heliophysics.jpg',
    subset: [],
  },
  planetary: {
    id: 'planetary',
    facetKey: 'planetary',
    searchQueryValue: 'planetary',
    label: 'Planetary Science',
    image: '/images/browse/discipline/planetary-science.jpg',
    subset: [],
  },
};

export const explorerFacets: Record<IExplorerCollection['id'], IExplorerFacet[]> = {
  database: [databases.astronomy, databases.physics, databases.earthscience, databases.general],

  doctype: [
    {
      label: 'e-print',
      icon: EPrintIcon,
      id: 'e-print',
      facetKey: '1/Article/e-print',
      searchQueryValue: 'eprint',
    },
    {
      label: 'Journal Articles',
      icon: JournalArticleIcon,
      id: 'Journal Article',
      facetKey: '1/Article/Journal Article',
      searchQueryValue: 'article',
    },
    {
      label: 'Datasets',
      icon: DatasetIcon,
      id: 'Dataset',
      facetKey: '1/Non-Article/Dataset',
      searchQueryValue: 'dataset',
    },
    {
      label: 'Software',
      icon: SoftwareIcon,
      id: 'Software',
      facetKey: '1/Non-Article/Software',
      searchQueryValue: 'software',
    },
  ],
  bibgroup: [
    { label: 'USGS', icon: UsgsIcon, id: 'USGS', facetKey: 'USGS', searchQueryValue: 'USGS' },
    { label: 'JWST', icon: JwstIcon, id: 'JWST', facetKey: 'JWST', searchQueryValue: 'JWST' },
    {
      label: 'NASA PubSpace',
      icon: NasaIcon,
      id: 'NASA PubSpace',
      facetKey: 'NASA PubSpace',
      searchQueryValue: 'NASA PubSpace',
    },
    { label: 'SETI', icon: SetiIcon, id: 'SETI', facetKey: 'SETI', searchQueryValue: 'SETI' },
  ],
  data: [
    { label: 'SIMBAD', icon: AstroDataIcon, id: 'SIMBAD', facetKey: 'SIMBAD', searchQueryValue: 'SIMBAD' },
    { label: 'MAST', icon: AstroDataIcon, id: 'MAST', facetKey: 'MAST', searchQueryValue: 'MAST' },
    { label: 'HEASARC', icon: AstroDataIcon, id: 'HEASARC', facetKey: 'HEASARC', searchQueryValue: 'HEASARC' },
    { label: 'NOAA', icon: ClimateIcon, id: 'NOAA', facetKey: 'NOAA', searchQueryValue: 'NOAA' },
  ],
};
