import {
  AstroDataIcon,
  InstitutionIcon,
  TelescopeIcon,
  ClimateIcon,
  EnvironmentIcon,
  PlanetaryIcon,
  EarthObservationIcon,
  GeoscienceIcon,
  HeliophysicsIcon,
  OceanIcon,
  SoftwareIcon,
} from '../icons/browser/data';
import { IFacetDetail } from './types';

export const dataDetails: Record<string, IFacetDetail> = {
  SIMBAD: { facetKey: 'SIMBAD', title: 'SIMBAD Astronomical Database', icon: AstroDataIcon },
  NED: { facetKey: 'NED', title: 'NASA/IPAC Extragalactic Database', icon: AstroDataIcon },
  MAST: { facetKey: 'MAST', title: 'Mikulski Archive for Space Telescopes', icon: AstroDataIcon },
  TNS: { facetKey: 'TNS', title: 'Transient Name Server', icon: AstroDataIcon },
  CDS: { facetKey: 'CDS', title: 'Strasbourg Astronomical Data Center', icon: AstroDataIcon },
  IRSA: { facetKey: 'IRSA', title: 'NASA/IPAC Infrared Science Archive', icon: AstroDataIcon },
  ESA: { facetKey: 'ESA', title: 'European Space Agency', icon: InstitutionIcon },
  HEASARC: { facetKey: 'HEASARC', title: 'High Energy Astrophysics Archive', icon: AstroDataIcon },
  ESO: { facetKey: 'ESO', title: 'European Southern Observatory', icon: TelescopeIcon },
  Chandra: { facetKey: 'Chandra', title: 'Chandra Data Archive', icon: TelescopeIcon },
  XMM: { facetKey: 'XMM', title: 'XMM-Newton Science Archive', icon: TelescopeIcon },
  NOAA: { facetKey: 'NOAA', title: 'NOAA Data', icon: ClimateIcon },
  'ORNL.DAAC': { facetKey: 'ORNL.DAAC', title: 'NASA Earth & Ecosystem Data', icon: EnvironmentIcon },
  vizier: { facetKey: 'vizier', title: 'VizieR Astronomical Catalogs', icon: AstroDataIcon },
  ALMA: { facetKey: 'ALMA', title: 'ALMA Science Archive', icon: TelescopeIcon },
  GSFC: { facetKey: 'GSFC', title: 'NASA Goddard', icon: InstitutionIcon },
  PDS: { facetKey: 'PDS', title: 'Planetary Data System', icon: PlanetaryIcon },
  KOA: { facetKey: 'KOA', title: 'Keck Observatory Archive', icon: TelescopeIcon },
  Gemini: { facetKey: 'Gemini', title: 'Gemini Science Archive', icon: TelescopeIcon },
  CopernicusEU: { facetKey: 'CopernicusEU', title: 'Copernicus Earth Observation Data', icon: EarthObservationIcon },
  USGS: { facetKey: 'USGS', title: 'U.S. Geological Survey', icon: GeoscienceIcon },
  NOAO: { facetKey: 'NOAO', title: 'NOAO Science Archive', icon: TelescopeIcon },
  GCPD: { facetKey: 'GCPD', title: 'General Catalogue of Photometric Data', icon: AstroDataIcon },
  Spitzer: { facetKey: 'Spitzer', title: 'Spitzer Data Archive', icon: TelescopeIcon },
  'GESDISC.DAAC': { facetKey: 'GESDISC.DAAC', title: 'NASA Atmosphere & Climate Data', icon: ClimateIcon },
  INES: { facetKey: 'INES', title: 'IUE Newly Extracted Spectra', icon: AstroDataIcon },
  'NASA.SPDF': { facetKey: 'NASA.SPDF', title: 'NASA Space Physics Data Facility', icon: HeliophysicsIcon },
  ATNF: { facetKey: 'ATNF', title: 'Australia Telescope Data', icon: TelescopeIcon },
  'ASDC.DAAC': { facetKey: 'ASDC.DAAC', title: 'NASA Atmospheric Science Data', icon: ClimateIcon },
  ECMWF: { facetKey: 'ECMWF', title: 'European Weather & Climate Data', icon: ClimateIcon },
  Astromat: { facetKey: 'Astromat', title: 'Astromaterials Data System', icon: PlanetaryIcon },
  LLNL: { facetKey: 'LLNL', title: 'Lawrence Livermore National Laboratory', icon: InstitutionIcon },
  ISO: { facetKey: 'ISO', title: 'Infrared Space Observatory', icon: TelescopeIcon },
  'PO.DAAC': { facetKey: 'PO.DAAC', title: 'NASA Physical Oceanography Data', icon: OceanIcon },
  JOSS: { facetKey: 'JOSS', title: 'Journal of Open Source Software', icon: InstitutionIcon },
  sedac: { facetKey: 'sedac', title: 'Socioeconomic Earth Science Data', icon: EnvironmentIcon },
  'NSIDC.DAAC': { facetKey: 'NSIDC.DAAC', title: 'NASA Snow & Ice Data Center', icon: ClimateIcon },
  NExScI: { facetKey: 'NExScI', title: 'NASA Exoplanet Science Institute', icon: AstroDataIcon },
  NASA: { facetKey: 'NASA', title: 'NASA Data', icon: InstitutionIcon },
  Herschel: { facetKey: 'Herschel', title: 'Herschel Science Archive', icon: TelescopeIcon },
  MetOffice: { facetKey: 'MetOffice', title: 'UK Met Office', icon: ClimateIcon },
  ARI: { facetKey: 'ARI', title: 'Astronomisches Rechen-Institut (?)', icon: AstroDataIcon },
  UCAR: { facetKey: 'UCAR', title: 'UCAR Earth System Data', icon: ClimateIcon },
  'OB.DAAC': { facetKey: 'OB.DAAC', title: 'NASA Ocean Biology Data', icon: OceanIcon },
  'LP.DAAC': { facetKey: 'LP.DAAC', title: 'NASA Land Processes Data', icon: EarthObservationIcon },
  Dryad: { facetKey: 'Dryad', title: 'Dryad Data Repository', icon: InstitutionIcon },
  PANGAEA: { facetKey: 'PANGAEA', title: 'PANGAEA Earth & Environmental Data', icon: GeoscienceIcon },
  HDRL: { facetKey: 'HDRL', title: 'Heliophysics Data Resource Library (?)', icon: HeliophysicsIcon },
  Google: { facetKey: 'Google', title: 'Google', icon: InstitutionIcon },
  StarGlass: { facetKey: 'StarGlass', title: 'StarGlass (?)', icon: AstroDataIcon },
  ColoState: { facetKey: 'ColoState', title: 'Colorado State University', icon: InstitutionIcon },
  DRYAD: { facetKey: 'DRYAD', title: '', icon: InstitutionIcon },
  'GHRC.DAAC': { facetKey: 'GHRC.DAAC', title: 'NASA Hydrometeorology Data', icon: ClimateIcon },
  NCAR: { facetKey: 'NCAR', title: 'National Center for Atmospheric Research', icon: ClimateIcon },
  CMDN: { facetKey: 'CMDN', title: 'Canadian Meteor Orbit Radar Data (?)', icon: HeliophysicsIcon },
  IRIS: { facetKey: 'IRIS', title: 'IRIS Seismological Data', icon: GeoscienceIcon },
  ipac: { facetKey: 'ipac', title: 'IPAC', icon: AstroDataIcon },
  'LAADS.DAAC': { facetKey: 'LAADS.DAAC', title: 'NASA Atmosphere Satellite Data', icon: EarthObservationIcon },
  NSIDC: { facetKey: 'NSIDC', title: 'National Snow & Ice Data Center', icon: ClimateIcon },
  UCSD: { facetKey: 'UCSD', title: 'UC San Diego', icon: InstitutionIcon },
  IBVS: { facetKey: 'IBVS', title: 'Information Bulletin on Variable Stars', icon: AstroDataIcon },
  CEDA: { facetKey: 'CEDA', title: 'UK Centre for Environmental Data Analysis', icon: ClimateIcon },
  GFZ: { facetKey: 'GFZ', title: 'GFZ German Research Centre for Geosciences', icon: GeoscienceIcon },
  GTC: { facetKey: 'GTC', title: 'Gran Telescopio Canarias', icon: TelescopeIcon },
  UEA: { facetKey: 'UEA', title: 'University of East Anglia', icon: InstitutionIcon },
  'SEDAC.DAAC': { facetKey: 'SEDAC.DAAC', title: 'NASA Socioeconomic Earth Data', icon: EnvironmentIcon },
  UHI: { facetKey: 'UHI', title: 'University of the Highlands and Islands', icon: InstitutionIcon },
  LaRC: { facetKey: 'LaRC', title: 'NASA Langley Research Center', icon: InstitutionIcon },
  EMAC: { facetKey: 'EMAC', title: 'Earth System Model Evaluation Tool (?)', icon: SoftwareIcon },
  EarthChem: { facetKey: 'EarthChem', title: 'EarthChem Geochemical Data', icon: GeoscienceIcon },
  TPDC: { facetKey: 'TPDC', title: 'Tibetan Plateau Data Center', icon: GeoscienceIcon },
  NERC: { facetKey: 'NERC', title: 'UK Natural Environment Research Council', icon: EnvironmentIcon },
  OPENMADRIGAL: { facetKey: 'OPENMADRIGAL', title: 'OpenMadrigal Upper Atmosphere Data', icon: HeliophysicsIcon },
  THEMIS: { facetKey: 'THEMIS', title: 'THEMIS Mission Data', icon: HeliophysicsIcon },
  FDSN: { facetKey: 'FDSN', title: 'Federation of Digital Seismograph Networks', icon: GeoscienceIcon },
  AVISO: { facetKey: 'AVISO', title: 'AVISO Satellite Altimetry Data', icon: OceanIcon },
  BoM: { facetKey: 'BoM', title: 'Australian Bureau of Meteorology', icon: ClimateIcon },
  '4TU.ResearchData': { facetKey: '4TU.ResearchData', title: '4TU.ResearchData', icon: InstitutionIcon },
  DKRZ: { facetKey: 'DKRZ', title: 'German Climate Computing Center', icon: ClimateIcon },
  Uiowa: { facetKey: 'Uiowa', title: 'University of Iowa', icon: InstitutionIcon },
  ColoradoState: { facetKey: 'ColoradoState', title: '', icon: InstitutionIcon },
  UNAVCO: { facetKey: 'UNAVCO', title: 'UNAVCO Geodetic Data', icon: GeoscienceIcon },
  Hydroshare: { facetKey: 'Hydroshare', title: 'HydroShare Water Data', icon: OceanIcon },
  JAXA: { facetKey: 'JAXA', title: 'Japan Aerospace Exploration Agency', icon: InstitutionIcon },
  NagoyaU: { facetKey: 'NagoyaU', title: 'Nagoya University', icon: InstitutionIcon },
  'IMD Pune': { facetKey: 'IMD Pune', title: 'India Meteorological Department', icon: ClimateIcon },
  NCEI: { facetKey: 'NCEI', title: 'NOAA Environmental Data', icon: ClimateIcon },
  RSS: { facetKey: 'RSS', title: 'Remote Sensing Systems', icon: EarthObservationIcon },
  GLEAM: { facetKey: 'GLEAM', title: 'Global Land Evaporation Data', icon: EnvironmentIcon },
  'Generic-Mapping-Tools': {
    facetKey: 'Generic-Mapping-Tools',
    title: 'Generic Mapping Tools (GMT)',
    icon: SoftwareIcon,
  },
  PIK: { facetKey: 'PIK', title: 'Potsdam Institute for Climate Research', icon: ClimateIcon },
  ETHZ: { facetKey: 'ETHZ', title: 'ETH Zürich', icon: InstitutionIcon },
  JHUAPL: { facetKey: 'JHUAPL', title: 'John Hopkins Applied Physics Lab', icon: InstitutionIcon },
  HYCOM: { facetKey: 'HYCOM', title: 'HYCOM Ocean Model Data', icon: OceanIcon },
  JAMSTEC: { facetKey: 'JAMSTEC', title: 'Japan Marine-Earth Science Data', icon: OceanIcon },
  ArcticData: { facetKey: 'ArcticData', title: 'Arctic Data Center', icon: ClimateIcon },
  Eurostat: { facetKey: 'Eurostat', title: 'Eurostat', icon: InstitutionIcon },
  WHOI: { facetKey: 'WHOI', title: 'Woods Hole Oceanographic Institution', icon: OceanIcon },
  MIT: { facetKey: 'MIT', title: 'MIT', icon: InstitutionIcon },
  'CDDIS.DAAC': { facetKey: 'CDDIS.DAAC', title: 'NASA Space Geodesy Data', icon: GeoscienceIcon },
  ColumbiaUni: { facetKey: 'ColumbiaUni', title: 'Columbia University', icon: InstitutionIcon },
  LBL: { facetKey: 'LBL', title: 'Lawrence Berkeley National Laboratory', icon: InstitutionIcon },
  IFREMER: { facetKey: 'IFREMER', title: 'IFREMER Marine Data', icon: OceanIcon },
  ASU: { facetKey: 'ASU', title: 'Arizona State University', icon: InstitutionIcon },
  'JRA-55': { facetKey: 'JRA-55', title: 'JRA-55 Atmospheric Reanalysis', icon: ClimateIcon },
  FLUXNET: { facetKey: 'FLUXNET', title: 'FLUXNET Ecosystem Data', icon: EnvironmentIcon },
  NGL: { facetKey: 'NGL', title: 'Nevada Geodetic Laboratory', icon: GeoscienceIcon },
  'BCO-DMO': { facetKey: 'BCO-DMO', title: 'Biological & Chemical Oceanography Data', icon: OceanIcon },
  CCDC: { facetKey: 'CCDC', title: 'Climate Change Data Center (?)', icon: ClimateIcon },
  UCBerkeley: { facetKey: 'UCBerkeley', title: 'UC Berkeley', icon: InstitutionIcon },
  ChinaVO: { facetKey: 'ChinaVO', title: 'China Virtual Observatory', icon: AstroDataIcon },
  DIAS: { facetKey: 'DIAS', title: 'DIAS Earth Observation Data', icon: EarthObservationIcon },
  INGV: { facetKey: 'INGV', title: 'Italian Geophysics & Volcanology Institute', icon: GeoscienceIcon },
  BerkeleyEarth: { facetKey: 'BerkeleyEarth', title: 'Berkeley Earth Climate Data', icon: ClimateIcon },
  UCF: { facetKey: 'UCF', title: 'University of Central Florida', icon: InstitutionIcon },
  SEDAC: { facetKey: 'SEDAC', title: '', icon: EnvironmentIcon },
  UMD: { facetKey: 'UMD', title: 'University of Maryland', icon: InstitutionIcon },
  SABER: { facetKey: 'SABER', title: 'SABER Atmospheric Data', icon: ClimateIcon },
  UMassLowell: { facetKey: 'UMassLowell', title: 'UMass Lowell', icon: InstitutionIcon },
  STSCI: { facetKey: 'STSCI', title: 'Space Telescope Science Institute', icon: AstroDataIcon },
  ARM: { facetKey: 'ARM', title: 'Atmospheric Radiation Measurement Data', icon: ClimateIcon },
  UCSB: { facetKey: 'UCSB', title: 'UC Santa Barbara', icon: InstitutionIcon },
  LMD: { facetKey: 'LMD', title: 'Laboratoire de Météorologie Dynamique', icon: ClimateIcon },
  Copernicus: { facetKey: 'Copernicus', title: 'Copernicus Climate & Earth Data', icon: EarthObservationIcon },
  INTERMAGNET: { facetKey: 'INTERMAGNET', title: 'Global Geomagnetic Observatory Data', icon: HeliophysicsIcon },
  CCRC: { facetKey: 'CCRC', title: 'Climate Change Research Centre', icon: ClimateIcon },
  EarthRef: { facetKey: 'EarthRef', title: 'EarthRef Geoscience Data', icon: GeoscienceIcon },
  IAP: { facetKey: 'IAP', title: 'Institute of Atmospheric Physics (?)', icon: ClimateIcon },
  GAVO: { facetKey: 'GAVO', title: 'German Astrophysical Virtual Observatory', icon: AstroDataIcon },
  IPSL: { facetKey: 'IPSL', title: 'Institut Pierre-Simon Laplace', icon: ClimateIcon },
  TDR: { facetKey: 'TDR', title: 'Texas Data Repository (?)', icon: InstitutionIcon },
  DeepBlue: { facetKey: 'DeepBlue', title: 'Deep Blue Data', icon: InstitutionIcon },
  WISC: { facetKey: 'WISC', title: 'University of Wisconsin', icon: InstitutionIcon },
  CEDC: { facetKey: 'CEDC', title: 'China Earthquake Data Center (?)', icon: GeoscienceIcon },
  KNMI: { facetKey: 'KNMI', title: 'Royal Netherlands Meteorological Institute', icon: ClimateIcon },
  Stanford: { facetKey: 'Stanford', title: 'Stanford University', icon: InstitutionIcon },
  MeridianProject: { facetKey: 'MeridianProject', title: 'Meridian Space Weather Project (?)', icon: HeliophysicsIcon },
  OceanOPS: { facetKey: 'OceanOPS', title: 'Global Ocean Observing Data', icon: OceanIcon },
  CIG: { facetKey: 'CIG', title: 'Computational Infrastructure for Geodynamics', icon: GeoscienceIcon },
  GRAS: { facetKey: 'GRAS', title: 'GRAS Satellite Data (?)', icon: ClimateIcon },
  UniTokyo: { facetKey: 'UniTokyo', title: 'University of Tokyo', icon: InstitutionIcon },
  BNU: { facetKey: 'BNU', title: 'Beijing Normal University', icon: InstitutionIcon },
  UNH: { facetKey: 'UNH', title: 'University of New Hampshire', icon: InstitutionIcon },
  GeoNet: { facetKey: 'GeoNet', title: 'New Zealand GeoNet', icon: GeoscienceIcon },
  ORFEUS: { facetKey: 'ORFEUS', title: 'European Seismological Data', icon: GeoscienceIcon },
  INCOIS: { facetKey: 'INCOIS', title: 'Indian National Ocean Information Services', icon: OceanIcon },
  UniCalgary: { facetKey: 'UniCalgary', title: 'University of Calgary', icon: InstitutionIcon },
  JPL: { facetKey: 'JPL', title: 'NASA Jet Propulsion Laboratory', icon: InstitutionIcon },
  Canada: { facetKey: 'Canada', title: 'Government of Canada Data (?)', icon: InstitutionIcon },
  BGS: { facetKey: 'BGS', title: 'British Geological Survey', icon: GeoscienceIcon },
  UniHamburg: { facetKey: 'UniHamburg', title: 'University of Hamburg', icon: InstitutionIcon },
  GNSSWHU: { facetKey: 'GNSSWHU', title: 'Wuhan University GNSS Data', icon: GeoscienceIcon },
  REMSS: { facetKey: 'REMSS', title: 'Remote Sensing Systems', icon: EarthObservationIcon },
  METNorway: { facetKey: 'METNorway', title: 'Norwegian Meteorological Institute', icon: ClimateIcon },
  IEDA: { facetKey: 'IEDA', title: 'Interdisciplinary Earth Data Alliance', icon: GeoscienceIcon },
  GNSS: { facetKey: 'GNSS', title: 'GNSS Geodetic Data', icon: GeoscienceIcon },
  CSTR: { facetKey: 'CSTR', title: 'CSTR (?)', icon: InstitutionIcon },
  IRI: { facetKey: 'IRI', title: 'International Research Institute for Climate', icon: ClimateIcon },
  CALTECH: { facetKey: 'CALTECH', title: 'Caltech', icon: InstitutionIcon },
  UniBe: { facetKey: 'UniBe', title: 'University of Bern', icon: InstitutionIcon },
  'ASF.DAAC': { facetKey: 'ASF.DAAC', title: 'NASA Radar & Polar Data', icon: EarthObservationIcon },
  BfG: { facetKey: 'BfG', title: 'German Federal Institute of Hydrology', icon: OceanIcon },
  HirosakiUni: { facetKey: 'HirosakiUni', title: 'Hirosaki University', icon: InstitutionIcon },
  CSIC: { facetKey: 'CSIC', title: 'Spanish National Research Council', icon: InstitutionIcon },
  'BCC-CMA': { facetKey: 'BCC-CMA', title: 'Beijing Climate Center', icon: ClimateIcon },
  UCLA: { facetKey: 'UCLA', title: 'UCLA', icon: InstitutionIcon },
  'CN-ARGO': { facetKey: 'CN-ARGO', title: 'China Argo Ocean Data', icon: OceanIcon },
  UW: { facetKey: 'UW', title: 'University of Washington', icon: InstitutionIcon },
  GMU: { facetKey: 'GMU', title: 'George Mason University', icon: InstitutionIcon },
  Harvard: { facetKey: 'Harvard', title: 'Harvard University', icon: InstitutionIcon },
  ISGI: { facetKey: 'ISGI', title: 'International Service of Geomagnetic Indices', icon: HeliophysicsIcon },
  NILU: { facetKey: 'NILU', title: 'Norwegian Institute for Air Research', icon: ClimateIcon },
  JASMIN: { facetKey: 'JASMIN', title: 'JASMIN Environmental Data', icon: ClimateIcon },
  Earthbyte: { facetKey: 'Earthbyte', title: 'EarthByte Geoscience Data', icon: GeoscienceIcon },
  GHDx: { facetKey: 'GHDx', title: 'Global Health Data Exchange', icon: InstitutionIcon },
  UMT: { facetKey: 'UMT', title: 'University of Montana', icon: InstitutionIcon },
  CDPP: { facetKey: 'CDPP', title: 'Plasma Physics Data Centre', icon: HeliophysicsIcon },
  'India-WRIS': { facetKey: 'India-WRIS', title: 'India Water Resources Data', icon: OceanIcon },
  MPG: { facetKey: 'MPG', title: 'Max Planck Society', icon: InstitutionIcon },
  ACRI: { facetKey: 'ACRI', title: 'ACRI Earth Observation Data', icon: EarthObservationIcon },
  AcA: { facetKey: 'AcA', title: 'Academia Sinica (?)', icon: InstitutionIcon },
  Dataverse: { facetKey: 'Dataverse', title: 'Dataverse Research Data', icon: InstitutionIcon },
  GBIF: { facetKey: 'GBIF', title: 'Global Biodiversity Data', icon: EnvironmentIcon },
  GlobalDamWatch: { facetKey: 'GlobalDamWatch', title: 'Global Dam Watch', icon: OceanIcon },
  IllinoisDataBank: { facetKey: 'IllinoisDataBank', title: 'Illinois Data Bank', icon: InstitutionIcon },
  UCI: { facetKey: 'UCI', title: 'UC Irvine', icon: InstitutionIcon },
  UniHawaii: { facetKey: 'UniHawaii', title: 'University of Hawaiʻi', icon: InstitutionIcon },
  WUSTL: { facetKey: 'WUSTL', title: 'Washington University in St. Louis', icon: InstitutionIcon },
  Inkscape: { facetKey: 'Inkscape', title: 'Inkscape', icon: SoftwareIcon },
  MagIC: { facetKey: 'MagIC', title: 'Magnetics Information Consortium', icon: GeoscienceIcon },
  'TexasA&M': { facetKey: 'TexasA&M', title: 'Texas A&M University', icon: InstitutionIcon },
  CARISMA: { facetKey: 'CARISMA', title: 'CARISMA Magnetometer Data', icon: HeliophysicsIcon },
  Rutgers: { facetKey: 'Rutgers', title: 'Rutgers University', icon: InstitutionIcon },
  UNB: { facetKey: 'UNB', title: 'University of New Brunswick', icon: InstitutionIcon },
  AmeriFlux: { facetKey: 'AmeriFlux', title: 'AmeriFlux Ecosystem Data', icon: EnvironmentIcon },
  EUREF: { facetKey: 'EUREF', title: 'European Geodetic Reference Data', icon: GeoscienceIcon },
  KyotoU: { facetKey: 'KyotoU', title: 'Kyoto University', icon: InstitutionIcon },
  DTU: { facetKey: 'DTU', title: 'Technical University of Denmark', icon: InstitutionIcon },
  FluxCom: { facetKey: 'FluxCom', title: 'FLUXCOM Carbon & Energy Fluxes', icon: EnvironmentIcon },
  UCoBoulder: { facetKey: 'UCoBoulder', title: 'University of Colorado Boulder', icon: InstitutionIcon },
  NBSC: { facetKey: 'NBSC', title: 'National Bureau of Statistics of China', icon: InstitutionIcon },
  StockholmUni: { facetKey: 'StockholmUni', title: 'Stockholm University', icon: InstitutionIcon },
  TUGraz: { facetKey: 'TUGraz', title: 'Graz University of Technology', icon: InstitutionIcon },
  'equake-rc': { facetKey: 'equake-rc', title: 'Earthquake Research Data (?)', icon: GeoscienceIcon },
  Geochron: { facetKey: 'Geochron', title: 'Geochronology Data', icon: GeoscienceIcon },
  NIES: { facetKey: 'NIES', title: 'National Institute for Environmental Studies', icon: EnvironmentIcon },
  Oulu: { facetKey: 'Oulu', title: 'University of Oulu', icon: InstitutionIcon },
  AAS: { facetKey: 'AAS', title: 'American Astronomical Society', icon: InstitutionIcon },
  TAMUCC: { facetKey: 'TAMUCC', title: 'Texas A&M–Corpus Christi', icon: InstitutionIcon },
  TsinghuaUni: { facetKey: 'TsinghuaUni', title: 'Tsinghua University', icon: InstitutionIcon },
  UMICH: { facetKey: 'UMICH', title: 'University of Michigan', icon: InstitutionIcon },
  UMN: { facetKey: 'UMN', title: 'University of Minnesota', icon: InstitutionIcon },
  USDOE: { facetKey: 'USDOE', title: 'U.S. Department of Energy', icon: InstitutionIcon },
  GATS: { facetKey: 'GATS', title: 'GATS Atmospheric Data (?)', icon: ClimateIcon },
  GeoHK: { facetKey: 'GeoHK', title: 'Hong Kong Geospatial Data (?)', icon: GeoscienceIcon },
  OpenEI: { facetKey: 'OpenEI', title: 'Open Energy Information', icon: EnvironmentIcon },
  IBGE: { facetKey: 'IBGE', title: 'Brazilian Institute of Geography & Statistics', icon: InstitutionIcon },
  NSO: { facetKey: 'NSO', title: 'National Solar Observatory', icon: TelescopeIcon },
  source: { facetKey: 'source', title: 'Source Data (?)', icon: InstitutionIcon },
  'EIDA INGV': { facetKey: 'EIDA INGV', title: 'INGV European Seismic Data', icon: GeoscienceIcon },
  'SPBU-RU': { facetKey: 'SPBU-RU', title: 'St. Petersburg State University', icon: InstitutionIcon },
  AMISR: { facetKey: 'AMISR', title: 'Advanced Modular Incoherent Scatter Radar', icon: HeliophysicsIcon },
  NWRA: { facetKey: 'NWRA', title: 'NorthWest Research Associates', icon: InstitutionIcon },
  UniArizona: { facetKey: 'UniArizona', title: 'University of Arizona', icon: InstitutionIcon },
  'ASDC-ASIM': { facetKey: 'ASDC-ASIM', title: 'ASIM Atmospheric Data', icon: ClimateIcon },
  GlobColour: { facetKey: 'GlobColour', title: 'GlobColour Ocean Color Data', icon: OceanIcon },
  ICTP: { facetKey: 'ICTP', title: 'International Centre for Theoretical Physics', icon: InstitutionIcon },
  UniLeicester: { facetKey: 'UniLeicester', title: 'University of Leicester', icon: InstitutionIcon },
  BGI: { facetKey: 'BGI', title: 'International Gravimetric Bureau', icon: GeoscienceIcon },
  Astroverse: { facetKey: 'Astroverse', title: 'Astroverse (?)', icon: AstroDataIcon },
  Geant4: { facetKey: 'Geant4', title: 'Geant4 Simulation Toolkit', icon: SoftwareIcon },
  NCI: { facetKey: 'NCI', title: 'Australian National Computational Infrastructure', icon: InstitutionIcon },
  SONEL: { facetKey: 'SONEL', title: 'Sea-Level GNSS Data', icon: GeoscienceIcon },
  UniChile: { facetKey: 'UniChile', title: 'University of Chile', icon: InstitutionIcon },
  NRCan: { facetKey: 'NRCan', title: 'Natural Resources Canada', icon: GeoscienceIcon },
  ParisObs: { facetKey: 'ParisObs', title: 'Paris Observatory', icon: TelescopeIcon },
  SCSIO: { facetKey: 'SCSIO', title: 'South China Sea Institute of Oceanology', icon: OceanIcon },
  UniUtah: { facetKey: 'UniUtah', title: 'University of Utah', icon: InstitutionIcon },
  IGN: { facetKey: 'IGN', title: 'IGN Geospatial Data', icon: GeoscienceIcon },
  'NASA.GeneLab': { facetKey: 'NASA.GeneLab', title: 'NASA GeneLab', icon: EnvironmentIcon },
  GPlates: { facetKey: 'GPlates', title: 'GPlates Plate Tectonics Data', icon: SoftwareIcon },
  NSMC: { facetKey: 'NSMC', title: 'National Satellite Meteorological Center', icon: EarthObservationIcon },
  SentinelHub: { facetKey: 'SentinelHub', title: 'Sentinel Hub Earth Observation Data', icon: EarthObservationIcon },
  UniTehran: { facetKey: 'UniTehran', title: 'University of Tehran', icon: InstitutionIcon },
  SESAR: { facetKey: 'SESAR', title: 'System for Earth Sample Registration', icon: PlanetaryIcon },
  'SRI International': { facetKey: 'SRI International', title: 'SRI International', icon: InstitutionIcon },
  ASTRON: { facetKey: 'ASTRON', title: 'Netherlands Institute for Radio Astronomy', icon: TelescopeIcon },
  CLWeb: { facetKey: 'CLWeb', title: 'CLWeb (?)', icon: InstitutionIcon },
  Formosat: { facetKey: 'Formosat', title: 'FORMOSAT Satellite Data', icon: EarthObservationIcon },
  GWDG: { facetKey: 'GWDG', title: 'Göttingen Scientific Data Services', icon: InstitutionIcon },
  IZMIRAN: { facetKey: 'IZMIRAN', title: 'Russian Institute of Terrestrial Magnetism', icon: HeliophysicsIcon },
  LASG: { facetKey: 'LASG', title: 'LASG Atmospheric Science Data', icon: ClimateIcon },
  NIST: { facetKey: 'NIST', title: 'National Institute of Standards & Technology', icon: InstitutionIcon },
  NLLOC: { facetKey: 'NLLOC', title: 'NonLinLoc Seismology Software', icon: SoftwareIcon },
  SNU: { facetKey: 'SNU', title: 'Seoul National University', icon: InstitutionIcon },
  'WRMC-BSRN': { facetKey: 'WRMC-BSRN', title: 'Baseline Surface Radiation Network', icon: ClimateIcon },
  protocols: { facetKey: 'protocols', title: 'Protocols.io (?)', icon: InstitutionIcon },
  CASEarth: { facetKey: 'CASEarth', title: 'CASEarth Earth Science Data', icon: EarthObservationIcon },
  GESLA: { facetKey: 'GESLA', title: 'Global Sea-Level Data', icon: OceanIcon },
  GSI: { facetKey: 'GSI', title: 'Geospatial Information Authority of Japan', icon: GeoscienceIcon },
  USGODAE: { facetKey: 'USGODAE', title: 'U.S. GODAE Ocean Data', icon: OceanIcon },
  UniWashington: { facetKey: 'UniWashington', title: 'University of Washington', icon: InstitutionIcon },
  Berkeley: { facetKey: 'Berkeley', title: '', icon: InstitutionIcon },
  CDEC: { facetKey: 'CDEC', title: 'California Water & Climate Data', icon: OceanIcon },
  'EIDA NOA': { facetKey: 'EIDA NOA', title: 'NOA European Seismic Data', icon: GeoscienceIcon },
  EUDP: { facetKey: 'EUDP', title: 'European Union Data Portal (?)', icon: InstitutionIcon },
  'GOV.UK': { facetKey: 'GOV.UK', title: 'UK Government Data', icon: InstitutionIcon },
  Meereisportal: { facetKey: 'Meereisportal', title: 'German Sea Ice Data', icon: ClimateIcon },
  PKU: { facetKey: 'PKU', title: 'Peking University', icon: InstitutionIcon },
  UniKansas: { facetKey: 'UniKansas', title: 'University of Kansas', icon: InstitutionIcon },
  AFREF: { facetKey: 'AFREF', title: 'African Geodetic Reference Frame', icon: GeoscienceIcon },
  'EIDA GFZ': { facetKey: 'EIDA GFZ', title: 'GFZ European Seismic Data', icon: GeoscienceIcon },
  GeoROC: { facetKey: 'GeoROC', title: 'Geochemistry of Rocks Database', icon: GeoscienceIcon },
  NII: { facetKey: 'NII', title: 'National Institute of Informatics', icon: InstitutionIcon },
  PDC: { facetKey: 'PDC', title: 'PDC (?)', icon: InstitutionIcon },
  'AVISO-CNES': { facetKey: 'AVISO-CNES', title: 'CNES AVISO Altimetry Data', icon: OceanIcon },
  AusPass: { facetKey: 'AusPass', title: 'Australian Seismological Data', icon: GeoscienceIcon },
  ERDC: { facetKey: 'ERDC', title: 'U.S. Army Engineer Research Center', icon: InstitutionIcon },
  GOTM: { facetKey: 'GOTM', title: 'General Ocean Turbulence Model', icon: SoftwareIcon },
  PSU: { facetKey: 'PSU', title: 'Penn State University', icon: InstitutionIcon },
  SWRI: { facetKey: 'SWRI', title: 'Southwest Research Institute', icon: InstitutionIcon },
  eartH2Observe: { facetKey: 'eartH2Observe', title: 'Global Hydrological Data', icon: OceanIcon },
};
