import {
  AstroDataIcon,
  InstitutionIcon,
  TelescopeIcon,
  ClimateIcon,
  EnvironmentIcon,
  PlanetaryIcon,
  EarthObservationIcon,
  GeoscienceIcon,
  HeliophysicsIcon,
  OceanIcon,
  SoftwareIcon,
} from '../icons/browser/data';
import { IFacetDescription } from './types';

export const dataDescriptions: Record<string, IFacetDescription> = {
  SIMBAD: { facetKey: 'SIMBAD', desc: 'SIMBAD Astronomical Database', icon: AstroDataIcon },
  NED: { facetKey: 'NED', desc: 'NASA/IPAC Extragalactic Database', icon: AstroDataIcon },
  MAST: { facetKey: 'MAST', desc: 'Mikulski Archive for Space Telescopes', icon: AstroDataIcon },
  TNS: { facetKey: 'TNS', desc: 'Transient Name Server', icon: AstroDataIcon },
  CDS: { facetKey: 'CDS', desc: 'Strasbourg Astronomical Data Center', icon: AstroDataIcon },
  IRSA: { facetKey: 'IRSA', desc: 'NASA/IPAC Infrared Science Archive', icon: AstroDataIcon },
  ESA: { facetKey: 'ESA', desc: 'European Space Agency', icon: InstitutionIcon },
  HEASARC: { facetKey: 'HEASARC', desc: 'High Energy Astrophysics Archive', icon: AstroDataIcon },
  ESO: { facetKey: 'ESO', desc: 'European Southern Observatory', icon: TelescopeIcon },
  Chandra: { facetKey: 'Chandra', desc: 'Chandra Data Archive', icon: TelescopeIcon },
  XMM: { facetKey: 'XMM', desc: 'XMM-Newton Science Archive', icon: TelescopeIcon },
  NOAA: { facetKey: 'NOAA', desc: 'NOAA Data', icon: ClimateIcon },
  'ORNL.DAAC': { facetKey: 'ORNL.DAAC', desc: 'NASA Earth & Ecosystem Data', icon: EnvironmentIcon },
  vizier: { facetKey: 'vizier', desc: 'VizieR Astronomical Catalogs', icon: AstroDataIcon },
  ALMA: { facetKey: 'ALMA', desc: 'ALMA Science Archive', icon: TelescopeIcon },
  GSFC: { facetKey: 'GSFC', desc: 'NASA Goddard', icon: InstitutionIcon },
  PDS: { facetKey: 'PDS', desc: 'Planetary Data System', icon: PlanetaryIcon },
  KOA: { facetKey: 'KOA', desc: 'Keck Observatory Archive', icon: TelescopeIcon },
  Gemini: { facetKey: 'Gemini', desc: 'Gemini Science Archive', icon: TelescopeIcon },
  CopernicusEU: { facetKey: 'CopernicusEU', desc: 'Copernicus Earth Observation Data', icon: EarthObservationIcon },
  USGS: { facetKey: 'USGS', desc: 'U.S. Geological Survey', icon: GeoscienceIcon },
  NOAO: { facetKey: 'NOAO', desc: 'NOAO Science Archive', icon: TelescopeIcon },
  GCPD: { facetKey: 'GCPD', desc: 'General Catalogue of Photometric Data', icon: AstroDataIcon },
  Spitzer: { facetKey: 'Spitzer', desc: 'Spitzer Data Archive', icon: TelescopeIcon },
  'GESDISC.DAAC': { facetKey: 'GESDISC.DAAC', desc: 'NASA Atmosphere & Climate Data', icon: ClimateIcon },
  INES: { facetKey: 'INES', desc: 'IUE Newly Extracted Spectra', icon: AstroDataIcon },
  'NASA.SPDF': { facetKey: 'NASA.SPDF', desc: 'NASA Space Physics Data Facility', icon: HeliophysicsIcon },
  ATNF: { facetKey: 'ATNF', desc: 'Australia Telescope Data', icon: TelescopeIcon },
  'ASDC.DAAC': { facetKey: 'ASDC.DAAC', desc: 'NASA Atmospheric Science Data', icon: ClimateIcon },
  ECMWF: { facetKey: 'ECMWF', desc: 'European Weather & Climate Data', icon: ClimateIcon },
  Astromat: { facetKey: 'Astromat', desc: 'Astromaterials Data System', icon: PlanetaryIcon },
  LLNL: { facetKey: 'LLNL', desc: 'Lawrence Livermore National Laboratory', icon: InstitutionIcon },
  ISO: { facetKey: 'ISO', desc: 'Infrared Space Observatory', icon: TelescopeIcon },
  'PO.DAAC': { facetKey: 'PO.DAAC', desc: 'NASA Physical Oceanography Data', icon: OceanIcon },
  JOSS: { facetKey: 'JOSS', desc: 'Journal of Open Source Software', icon: InstitutionIcon },
  sedac: { facetKey: 'sedac', desc: 'Socioeconomic Earth Science Data', icon: EnvironmentIcon },
  'NSIDC.DAAC': { facetKey: 'NSIDC.DAAC', desc: 'NASA Snow & Ice Data Center', icon: ClimateIcon },
  NExScI: { facetKey: 'NExScI', desc: 'NASA Exoplanet Science Institute', icon: AstroDataIcon },
  NASA: { facetKey: 'NASA', desc: 'NASA Data', icon: InstitutionIcon },
  Herschel: { facetKey: 'Herschel', desc: 'Herschel Science Archive', icon: TelescopeIcon },
  MetOffice: { facetKey: 'MetOffice', desc: 'UK Met Office', icon: ClimateIcon },
  ARI: { facetKey: 'ARI', desc: 'Astronomisches Rechen-Institut (?)', icon: AstroDataIcon },
  UCAR: { facetKey: 'UCAR', desc: 'UCAR Earth System Data', icon: ClimateIcon },
  'OB.DAAC': { facetKey: 'OB.DAAC', desc: 'NASA Ocean Biology Data', icon: OceanIcon },
  'LP.DAAC': { facetKey: 'LP.DAAC', desc: 'NASA Land Processes Data', icon: EarthObservationIcon },
  Dryad: { facetKey: 'Dryad', desc: 'Dryad Data Repository', icon: InstitutionIcon },
  PANGAEA: { facetKey: 'PANGAEA', desc: 'PANGAEA Earth & Environmental Data', icon: GeoscienceIcon },
  HDRL: { facetKey: 'HDRL', desc: 'Heliophysics Data Resource Library (?)', icon: HeliophysicsIcon },
  Google: { facetKey: 'Google', desc: 'Google', icon: InstitutionIcon },
  StarGlass: { facetKey: 'StarGlass', desc: 'StarGlass (?)', icon: AstroDataIcon },
  ColoState: { facetKey: 'ColoState', desc: 'Colorado State University', icon: InstitutionIcon },
  DRYAD: { facetKey: 'DRYAD', desc: '', icon: InstitutionIcon },
  'GHRC.DAAC': { facetKey: 'GHRC.DAAC', desc: 'NASA Hydrometeorology Data', icon: ClimateIcon },
  NCAR: { facetKey: 'NCAR', desc: 'National Center for Atmospheric Research', icon: ClimateIcon },
  CMDN: { facetKey: 'CMDN', desc: 'Canadian Meteor Orbit Radar Data (?)', icon: HeliophysicsIcon },
  IRIS: { facetKey: 'IRIS', desc: 'IRIS Seismological Data', icon: GeoscienceIcon },
  ipac: { facetKey: 'ipac', desc: 'IPAC', icon: AstroDataIcon },
  'LAADS.DAAC': { facetKey: 'LAADS.DAAC', desc: 'NASA Atmosphere Satellite Data', icon: EarthObservationIcon },
  NSIDC: { facetKey: 'NSIDC', desc: 'National Snow & Ice Data Center', icon: ClimateIcon },
  UCSD: { facetKey: 'UCSD', desc: 'UC San Diego', icon: InstitutionIcon },
  IBVS: { facetKey: 'IBVS', desc: 'Information Bulletin on Variable Stars', icon: AstroDataIcon },
  CEDA: { facetKey: 'CEDA', desc: 'UK Centre for Environmental Data Analysis', icon: ClimateIcon },
  GFZ: { facetKey: 'GFZ', desc: 'GFZ German Research Centre for Geosciences', icon: GeoscienceIcon },
  GTC: { facetKey: 'GTC', desc: 'Gran Telescopio Canarias', icon: TelescopeIcon },
  UEA: { facetKey: 'UEA', desc: 'University of East Anglia', icon: InstitutionIcon },
  'SEDAC.DAAC': { facetKey: 'SEDAC.DAAC', desc: 'NASA Socioeconomic Earth Data', icon: EnvironmentIcon },
  UHI: { facetKey: 'UHI', desc: 'University of the Highlands and Islands', icon: InstitutionIcon },
  LaRC: { facetKey: 'LaRC', desc: 'NASA Langley Research Center', icon: InstitutionIcon },
  EMAC: { facetKey: 'EMAC', desc: 'Earth System Model Evaluation Tool (?)', icon: SoftwareIcon },
  EarthChem: { facetKey: 'EarthChem', desc: 'EarthChem Geochemical Data', icon: GeoscienceIcon },
  TPDC: { facetKey: 'TPDC', desc: 'Tibetan Plateau Data Center', icon: GeoscienceIcon },
  NERC: { facetKey: 'NERC', desc: 'UK Natural Environment Research Council', icon: EnvironmentIcon },
  OPENMADRIGAL: { facetKey: 'OPENMADRIGAL', desc: 'OpenMadrigal Upper Atmosphere Data', icon: HeliophysicsIcon },
  THEMIS: { facetKey: 'THEMIS', desc: 'THEMIS Mission Data', icon: HeliophysicsIcon },
  FDSN: { facetKey: 'FDSN', desc: 'Federation of Digital Seismograph Networks', icon: GeoscienceIcon },
  AVISO: { facetKey: 'AVISO', desc: 'AVISO Satellite Altimetry Data', icon: OceanIcon },
  BoM: { facetKey: 'BoM', desc: 'Australian Bureau of Meteorology', icon: ClimateIcon },
  '4TU.ResearchData': { facetKey: '4TU.ResearchData', desc: '4TU.ResearchData', icon: InstitutionIcon },
  DKRZ: { facetKey: 'DKRZ', desc: 'German Climate Computing Center', icon: ClimateIcon },
  Uiowa: { facetKey: 'Uiowa', desc: 'University of Iowa', icon: InstitutionIcon },
  ColoradoState: { facetKey: 'ColoradoState', desc: '', icon: InstitutionIcon },
  UNAVCO: { facetKey: 'UNAVCO', desc: 'UNAVCO Geodetic Data', icon: GeoscienceIcon },
  Hydroshare: { facetKey: 'Hydroshare', desc: 'HydroShare Water Data', icon: OceanIcon },
  JAXA: { facetKey: 'JAXA', desc: 'Japan Aerospace Exploration Agency', icon: InstitutionIcon },
  NagoyaU: { facetKey: 'NagoyaU', desc: 'Nagoya University', icon: InstitutionIcon },
  'IMD Pune': { facetKey: 'IMD Pune', desc: 'India Meteorological Department', icon: ClimateIcon },
  NCEI: { facetKey: 'NCEI', desc: 'NOAA Environmental Data', icon: ClimateIcon },
  RSS: { facetKey: 'RSS', desc: 'Remote Sensing Systems', icon: EarthObservationIcon },
  GLEAM: { facetKey: 'GLEAM', desc: 'Global Land Evaporation Data', icon: EnvironmentIcon },
  'Generic-Mapping-Tools': {
    facetKey: 'Generic-Mapping-Tools',
    desc: 'Generic Mapping Tools (GMT)',
    icon: SoftwareIcon,
  },
  PIK: { facetKey: 'PIK', desc: 'Potsdam Institute for Climate Research', icon: ClimateIcon },
  ETHZ: { facetKey: 'ETHZ', desc: 'ETH Zürich', icon: InstitutionIcon },
  JHUAPL: { facetKey: 'JHUAPL', desc: 'John Hopkins Applied Physics Lab', icon: InstitutionIcon },
  HYCOM: { facetKey: 'HYCOM', desc: 'HYCOM Ocean Model Data', icon: OceanIcon },
  JAMSTEC: { facetKey: 'JAMSTEC', desc: 'Japan Marine-Earth Science Data', icon: OceanIcon },
  ArcticData: { facetKey: 'ArcticData', desc: 'Arctic Data Center', icon: ClimateIcon },
  Eurostat: { facetKey: 'Eurostat', desc: 'Eurostat', icon: InstitutionIcon },
  WHOI: { facetKey: 'WHOI', desc: 'Woods Hole Oceanographic Institution', icon: OceanIcon },
  MIT: { facetKey: 'MIT', desc: 'MIT', icon: InstitutionIcon },
  'CDDIS.DAAC': { facetKey: 'CDDIS.DAAC', desc: 'NASA Space Geodesy Data', icon: GeoscienceIcon },
  ColumbiaUni: { facetKey: 'ColumbiaUni', desc: 'Columbia University', icon: InstitutionIcon },
  LBL: { facetKey: 'LBL', desc: 'Lawrence Berkeley National Laboratory', icon: InstitutionIcon },
  IFREMER: { facetKey: 'IFREMER', desc: 'IFREMER Marine Data', icon: OceanIcon },
  ASU: { facetKey: 'ASU', desc: 'Arizona State University', icon: InstitutionIcon },
  'JRA-55': { facetKey: 'JRA-55', desc: 'JRA-55 Atmospheric Reanalysis', icon: ClimateIcon },
  FLUXNET: { facetKey: 'FLUXNET', desc: 'FLUXNET Ecosystem Data', icon: EnvironmentIcon },
  NGL: { facetKey: 'NGL', desc: 'Nevada Geodetic Laboratory', icon: GeoscienceIcon },
  'BCO-DMO': { facetKey: 'BCO-DMO', desc: 'Biological & Chemical Oceanography Data', icon: OceanIcon },
  CCDC: { facetKey: 'CCDC', desc: 'Climate Change Data Center (?)', icon: ClimateIcon },
  UCBerkeley: { facetKey: 'UCBerkeley', desc: 'UC Berkeley', icon: InstitutionIcon },
  ChinaVO: { facetKey: 'ChinaVO', desc: 'China Virtual Observatory', icon: AstroDataIcon },
  DIAS: { facetKey: 'DIAS', desc: 'DIAS Earth Observation Data', icon: EarthObservationIcon },
  INGV: { facetKey: 'INGV', desc: 'Italian Geophysics & Volcanology Institute', icon: GeoscienceIcon },
  BerkeleyEarth: { facetKey: 'BerkeleyEarth', desc: 'Berkeley Earth Climate Data', icon: ClimateIcon },
  UCF: { facetKey: 'UCF', desc: 'University of Central Florida', icon: InstitutionIcon },
  SEDAC: { facetKey: 'SEDAC', desc: '', icon: EnvironmentIcon },
  UMD: { facetKey: 'UMD', desc: 'University of Maryland', icon: InstitutionIcon },
  SABER: { facetKey: 'SABER', desc: 'SABER Atmospheric Data', icon: ClimateIcon },
  UMassLowell: { facetKey: 'UMassLowell', desc: 'UMass Lowell', icon: InstitutionIcon },
  STSCI: { facetKey: 'STSCI', desc: 'Space Telescope Science Institute', icon: AstroDataIcon },
  ARM: { facetKey: 'ARM', desc: 'Atmospheric Radiation Measurement Data', icon: ClimateIcon },
  UCSB: { facetKey: 'UCSB', desc: 'UC Santa Barbara', icon: InstitutionIcon },
  LMD: { facetKey: 'LMD', desc: 'Laboratoire de Météorologie Dynamique', icon: ClimateIcon },
  Copernicus: { facetKey: 'Copernicus', desc: 'Copernicus Climate & Earth Data', icon: EarthObservationIcon },
  INTERMAGNET: { facetKey: 'INTERMAGNET', desc: 'Global Geomagnetic Observatory Data', icon: HeliophysicsIcon },
  CCRC: { facetKey: 'CCRC', desc: 'Climate Change Research Centre', icon: ClimateIcon },
  EarthRef: { facetKey: 'EarthRef', desc: 'EarthRef Geoscience Data', icon: GeoscienceIcon },
  IAP: { facetKey: 'IAP', desc: 'Institute of Atmospheric Physics (?)', icon: ClimateIcon },
  GAVO: { facetKey: 'GAVO', desc: 'German Astrophysical Virtual Observatory', icon: AstroDataIcon },
  IPSL: { facetKey: 'IPSL', desc: 'Institut Pierre-Simon Laplace', icon: ClimateIcon },
  TDR: { facetKey: 'TDR', desc: 'Texas Data Repository (?)', icon: InstitutionIcon },
  DeepBlue: { facetKey: 'DeepBlue', desc: 'Deep Blue Data', icon: InstitutionIcon },
  WISC: { facetKey: 'WISC', desc: 'University of Wisconsin', icon: InstitutionIcon },
  CEDC: { facetKey: 'CEDC', desc: 'China Earthquake Data Center (?)', icon: GeoscienceIcon },
  KNMI: { facetKey: 'KNMI', desc: 'Royal Netherlands Meteorological Institute', icon: ClimateIcon },
  Stanford: { facetKey: 'Stanford', desc: 'Stanford University', icon: InstitutionIcon },
  MeridianProject: { facetKey: 'MeridianProject', desc: 'Meridian Space Weather Project (?)', icon: HeliophysicsIcon },
  OceanOPS: { facetKey: 'OceanOPS', desc: 'Global Ocean Observing Data', icon: OceanIcon },
  CIG: { facetKey: 'CIG', desc: 'Computational Infrastructure for Geodynamics', icon: GeoscienceIcon },
  GRAS: { facetKey: 'GRAS', desc: 'GRAS Satellite Data (?)', icon: ClimateIcon },
  UniTokyo: { facetKey: 'UniTokyo', desc: 'University of Tokyo', icon: InstitutionIcon },
  BNU: { facetKey: 'BNU', desc: 'Beijing Normal University', icon: InstitutionIcon },
  UNH: { facetKey: 'UNH', desc: 'University of New Hampshire', icon: InstitutionIcon },
  GeoNet: { facetKey: 'GeoNet', desc: 'New Zealand GeoNet', icon: GeoscienceIcon },
  ORFEUS: { facetKey: 'ORFEUS', desc: 'European Seismological Data', icon: GeoscienceIcon },
  INCOIS: { facetKey: 'INCOIS', desc: 'Indian National Ocean Information Services', icon: OceanIcon },
  UniCalgary: { facetKey: 'UniCalgary', desc: 'University of Calgary', icon: InstitutionIcon },
  JPL: { facetKey: 'JPL', desc: 'NASA Jet Propulsion Laboratory', icon: InstitutionIcon },
  Canada: { facetKey: 'Canada', desc: 'Government of Canada Data (?)', icon: InstitutionIcon },
  BGS: { facetKey: 'BGS', desc: 'British Geological Survey', icon: GeoscienceIcon },
  UniHamburg: { facetKey: 'UniHamburg', desc: 'University of Hamburg', icon: InstitutionIcon },
  GNSSWHU: { facetKey: 'GNSSWHU', desc: 'Wuhan University GNSS Data', icon: GeoscienceIcon },
  REMSS: { facetKey: 'REMSS', desc: 'Remote Sensing Systems', icon: EarthObservationIcon },
  METNorway: { facetKey: 'METNorway', desc: 'Norwegian Meteorological Institute', icon: ClimateIcon },
  IEDA: { facetKey: 'IEDA', desc: 'Interdisciplinary Earth Data Alliance', icon: GeoscienceIcon },
  GNSS: { facetKey: 'GNSS', desc: 'GNSS Geodetic Data', icon: GeoscienceIcon },
  CSTR: { facetKey: 'CSTR', desc: 'CSTR (?)', icon: InstitutionIcon },
  IRI: { facetKey: 'IRI', desc: 'International Research Institute for Climate', icon: ClimateIcon },
  CALTECH: { facetKey: 'CALTECH', desc: 'Caltech', icon: InstitutionIcon },
  UniBe: { facetKey: 'UniBe', desc: 'University of Bern', icon: InstitutionIcon },
  'ASF.DAAC': { facetKey: 'ASF.DAAC', desc: 'NASA Radar & Polar Data', icon: EarthObservationIcon },
  BfG: { facetKey: 'BfG', desc: 'German Federal Institute of Hydrology', icon: OceanIcon },
  HirosakiUni: { facetKey: 'HirosakiUni', desc: 'Hirosaki University', icon: InstitutionIcon },
  CSIC: { facetKey: 'CSIC', desc: 'Spanish National Research Council', icon: InstitutionIcon },
  'BCC-CMA': { facetKey: 'BCC-CMA', desc: 'Beijing Climate Center', icon: ClimateIcon },
  UCLA: { facetKey: 'UCLA', desc: 'UCLA', icon: InstitutionIcon },
  'CN-ARGO': { facetKey: 'CN-ARGO', desc: 'China Argo Ocean Data', icon: OceanIcon },
  UW: { facetKey: 'UW', desc: 'University of Washington', icon: InstitutionIcon },
  GMU: { facetKey: 'GMU', desc: 'George Mason University', icon: InstitutionIcon },
  Harvard: { facetKey: 'Harvard', desc: 'Harvard University', icon: InstitutionIcon },
  ISGI: { facetKey: 'ISGI', desc: 'International Service of Geomagnetic Indices', icon: HeliophysicsIcon },
  NILU: { facetKey: 'NILU', desc: 'Norwegian Institute for Air Research', icon: ClimateIcon },
  JASMIN: { facetKey: 'JASMIN', desc: 'JASMIN Environmental Data', icon: ClimateIcon },
  Earthbyte: { facetKey: 'Earthbyte', desc: 'EarthByte Geoscience Data', icon: GeoscienceIcon },
  GHDx: { facetKey: 'GHDx', desc: 'Global Health Data Exchange', icon: InstitutionIcon },
  UMT: { facetKey: 'UMT', desc: 'University of Montana', icon: InstitutionIcon },
  CDPP: { facetKey: 'CDPP', desc: 'Plasma Physics Data Centre', icon: HeliophysicsIcon },
  'India-WRIS': { facetKey: 'India-WRIS', desc: 'India Water Resources Data', icon: OceanIcon },
  MPG: { facetKey: 'MPG', desc: 'Max Planck Society', icon: InstitutionIcon },
  ACRI: { facetKey: 'ACRI', desc: 'ACRI Earth Observation Data', icon: EarthObservationIcon },
  AcA: { facetKey: 'AcA', desc: 'Academia Sinica (?)', icon: InstitutionIcon },
  Dataverse: { facetKey: 'Dataverse', desc: 'Dataverse Research Data', icon: InstitutionIcon },
  GBIF: { facetKey: 'GBIF', desc: 'Global Biodiversity Data', icon: EnvironmentIcon },
  GlobalDamWatch: { facetKey: 'GlobalDamWatch', desc: 'Global Dam Watch', icon: OceanIcon },
  IllinoisDataBank: { facetKey: 'IllinoisDataBank', desc: 'Illinois Data Bank', icon: InstitutionIcon },
  UCI: { facetKey: 'UCI', desc: 'UC Irvine', icon: InstitutionIcon },
  UniHawaii: { facetKey: 'UniHawaii', desc: 'University of Hawaiʻi', icon: InstitutionIcon },
  WUSTL: { facetKey: 'WUSTL', desc: 'Washington University in St. Louis', icon: InstitutionIcon },
  Inkscape: { facetKey: 'Inkscape', desc: 'Inkscape', icon: SoftwareIcon },
  MagIC: { facetKey: 'MagIC', desc: 'Magnetics Information Consortium', icon: GeoscienceIcon },
  'TexasA&M': { facetKey: 'TexasA&M', desc: 'Texas A&M University', icon: InstitutionIcon },
  CARISMA: { facetKey: 'CARISMA', desc: 'CARISMA Magnetometer Data', icon: HeliophysicsIcon },
  Rutgers: { facetKey: 'Rutgers', desc: 'Rutgers University', icon: InstitutionIcon },
  UNB: { facetKey: 'UNB', desc: 'University of New Brunswick', icon: InstitutionIcon },
  AmeriFlux: { facetKey: 'AmeriFlux', desc: 'AmeriFlux Ecosystem Data', icon: EnvironmentIcon },
  EUREF: { facetKey: 'EUREF', desc: 'European Geodetic Reference Data', icon: GeoscienceIcon },
  KyotoU: { facetKey: 'KyotoU', desc: 'Kyoto University', icon: InstitutionIcon },
  DTU: { facetKey: 'DTU', desc: 'Technical University of Denmark', icon: InstitutionIcon },
  FluxCom: { facetKey: 'FluxCom', desc: 'FLUXCOM Carbon & Energy Fluxes', icon: EnvironmentIcon },
  UCoBoulder: { facetKey: 'UCoBoulder', desc: 'University of Colorado Boulder', icon: InstitutionIcon },
  NBSC: { facetKey: 'NBSC', desc: 'National Bureau of Statistics of China', icon: InstitutionIcon },
  StockholmUni: { facetKey: 'StockholmUni', desc: 'Stockholm University', icon: InstitutionIcon },
  TUGraz: { facetKey: 'TUGraz', desc: 'Graz University of Technology', icon: InstitutionIcon },
  'equake-rc': { facetKey: 'equake-rc', desc: 'Earthquake Research Data (?)', icon: GeoscienceIcon },
  Geochron: { facetKey: 'Geochron', desc: 'Geochronology Data', icon: GeoscienceIcon },
  NIES: { facetKey: 'NIES', desc: 'National Institute for Environmental Studies', icon: EnvironmentIcon },
  Oulu: { facetKey: 'Oulu', desc: 'University of Oulu', icon: InstitutionIcon },
  AAS: { facetKey: 'AAS', desc: 'American Astronomical Society', icon: InstitutionIcon },
  TAMUCC: { facetKey: 'TAMUCC', desc: 'Texas A&M–Corpus Christi', icon: InstitutionIcon },
  TsinghuaUni: { facetKey: 'TsinghuaUni', desc: 'Tsinghua University', icon: InstitutionIcon },
  UMICH: { facetKey: 'UMICH', desc: 'University of Michigan', icon: InstitutionIcon },
  UMN: { facetKey: 'UMN', desc: 'University of Minnesota', icon: InstitutionIcon },
  USDOE: { facetKey: 'USDOE', desc: 'U.S. Department of Energy', icon: InstitutionIcon },
  GATS: { facetKey: 'GATS', desc: 'GATS Atmospheric Data (?)', icon: ClimateIcon },
  GeoHK: { facetKey: 'GeoHK', desc: 'Hong Kong Geospatial Data (?)', icon: GeoscienceIcon },
  OpenEI: { facetKey: 'OpenEI', desc: 'Open Energy Information', icon: EnvironmentIcon },
  IBGE: { facetKey: 'IBGE', desc: 'Brazilian Institute of Geography & Statistics', icon: InstitutionIcon },
  NSO: { facetKey: 'NSO', desc: 'National Solar Observatory', icon: TelescopeIcon },
  source: { facetKey: 'source', desc: 'Source Data (?)', icon: InstitutionIcon },
  'EIDA INGV': { facetKey: 'EIDA INGV', desc: 'INGV European Seismic Data', icon: GeoscienceIcon },
  'SPBU-RU': { facetKey: 'SPBU-RU', desc: 'St. Petersburg State University', icon: InstitutionIcon },
  AMISR: { facetKey: 'AMISR', desc: 'Advanced Modular Incoherent Scatter Radar', icon: HeliophysicsIcon },
  NWRA: { facetKey: 'NWRA', desc: 'NorthWest Research Associates', icon: InstitutionIcon },
  UniArizona: { facetKey: 'UniArizona', desc: 'University of Arizona', icon: InstitutionIcon },
  'ASDC-ASIM': { facetKey: 'ASDC-ASIM', desc: 'ASIM Atmospheric Data', icon: ClimateIcon },
  GlobColour: { facetKey: 'GlobColour', desc: 'GlobColour Ocean Color Data', icon: OceanIcon },
  ICTP: { facetKey: 'ICTP', desc: 'International Centre for Theoretical Physics', icon: InstitutionIcon },
  UniLeicester: { facetKey: 'UniLeicester', desc: 'University of Leicester', icon: InstitutionIcon },
  BGI: { facetKey: 'BGI', desc: 'International Gravimetric Bureau', icon: GeoscienceIcon },
  Astroverse: { facetKey: 'Astroverse', desc: 'Astroverse (?)', icon: AstroDataIcon },
  Geant4: { facetKey: 'Geant4', desc: 'Geant4 Simulation Toolkit', icon: SoftwareIcon },
  NCI: { facetKey: 'NCI', desc: 'Australian National Computational Infrastructure', icon: InstitutionIcon },
  SONEL: { facetKey: 'SONEL', desc: 'Sea-Level GNSS Data', icon: GeoscienceIcon },
  UniChile: { facetKey: 'UniChile', desc: 'University of Chile', icon: InstitutionIcon },
  NRCan: { facetKey: 'NRCan', desc: 'Natural Resources Canada', icon: GeoscienceIcon },
  ParisObs: { facetKey: 'ParisObs', desc: 'Paris Observatory', icon: TelescopeIcon },
  SCSIO: { facetKey: 'SCSIO', desc: 'South China Sea Institute of Oceanology', icon: OceanIcon },
  UniUtah: { facetKey: 'UniUtah', desc: 'University of Utah', icon: InstitutionIcon },
  IGN: { facetKey: 'IGN', desc: 'IGN Geospatial Data', icon: GeoscienceIcon },
  'NASA.GeneLab': { facetKey: 'NASA.GeneLab', desc: 'NASA GeneLab', icon: EnvironmentIcon },
  GPlates: { facetKey: 'GPlates', desc: 'GPlates Plate Tectonics Data', icon: SoftwareIcon },
  NSMC: { facetKey: 'NSMC', desc: 'National Satellite Meteorological Center', icon: EarthObservationIcon },
  SentinelHub: { facetKey: 'SentinelHub', desc: 'Sentinel Hub Earth Observation Data', icon: EarthObservationIcon },
  UniTehran: { facetKey: 'UniTehran', desc: 'University of Tehran', icon: InstitutionIcon },
  SESAR: { facetKey: 'SESAR', desc: 'System for Earth Sample Registration', icon: PlanetaryIcon },
  'SRI International': { facetKey: 'SRI International', desc: 'SRI International', icon: InstitutionIcon },
  ASTRON: { facetKey: 'ASTRON', desc: 'Netherlands Institute for Radio Astronomy', icon: TelescopeIcon },
  CLWeb: { facetKey: 'CLWeb', desc: 'CLWeb (?)', icon: InstitutionIcon },
  Formosat: { facetKey: 'Formosat', desc: 'FORMOSAT Satellite Data', icon: EarthObservationIcon },
  GWDG: { facetKey: 'GWDG', desc: 'Göttingen Scientific Data Services', icon: InstitutionIcon },
  IZMIRAN: { facetKey: 'IZMIRAN', desc: 'Russian Institute of Terrestrial Magnetism', icon: HeliophysicsIcon },
  LASG: { facetKey: 'LASG', desc: 'LASG Atmospheric Science Data', icon: ClimateIcon },
  NIST: { facetKey: 'NIST', desc: 'National Institute of Standards & Technology', icon: InstitutionIcon },
  NLLOC: { facetKey: 'NLLOC', desc: 'NonLinLoc Seismology Software', icon: SoftwareIcon },
  SNU: { facetKey: 'SNU', desc: 'Seoul National University', icon: InstitutionIcon },
  'WRMC-BSRN': { facetKey: 'WRMC-BSRN', desc: 'Baseline Surface Radiation Network', icon: ClimateIcon },
  protocols: { facetKey: 'protocols', desc: 'Protocols.io (?)', icon: InstitutionIcon },
  CASEarth: { facetKey: 'CASEarth', desc: 'CASEarth Earth Science Data', icon: EarthObservationIcon },
  GESLA: { facetKey: 'GESLA', desc: 'Global Sea-Level Data', icon: OceanIcon },
  GSI: { facetKey: 'GSI', desc: 'Geospatial Information Authority of Japan', icon: GeoscienceIcon },
  USGODAE: { facetKey: 'USGODAE', desc: 'U.S. GODAE Ocean Data', icon: OceanIcon },
  UniWashington: { facetKey: 'UniWashington', desc: 'University of Washington', icon: InstitutionIcon },
  Berkeley: { facetKey: 'Berkeley', desc: '', icon: InstitutionIcon },
  CDEC: { facetKey: 'CDEC', desc: 'California Water & Climate Data', icon: OceanIcon },
  'EIDA NOA': { facetKey: 'EIDA NOA', desc: 'NOA European Seismic Data', icon: GeoscienceIcon },
  EUDP: { facetKey: 'EUDP', desc: 'European Union Data Portal (?)', icon: InstitutionIcon },
  'GOV.UK': { facetKey: 'GOV.UK', desc: 'UK Government Data', icon: InstitutionIcon },
  Meereisportal: { facetKey: 'Meereisportal', desc: 'German Sea Ice Data', icon: ClimateIcon },
  PKU: { facetKey: 'PKU', desc: 'Peking University', icon: InstitutionIcon },
  UniKansas: { facetKey: 'UniKansas', desc: 'University of Kansas', icon: InstitutionIcon },
  AFREF: { facetKey: 'AFREF', desc: 'African Geodetic Reference Frame', icon: GeoscienceIcon },
  'EIDA GFZ': { facetKey: 'EIDA GFZ', desc: 'GFZ European Seismic Data', icon: GeoscienceIcon },
  GeoROC: { facetKey: 'GeoROC', desc: 'Geochemistry of Rocks Database', icon: GeoscienceIcon },
  NII: { facetKey: 'NII', desc: 'National Institute of Informatics', icon: InstitutionIcon },
  PDC: { facetKey: 'PDC', desc: 'PDC (?)', icon: InstitutionIcon },
  'AVISO-CNES': { facetKey: 'AVISO-CNES', desc: 'CNES AVISO Altimetry Data', icon: OceanIcon },
  AusPass: { facetKey: 'AusPass', desc: 'Australian Seismological Data', icon: GeoscienceIcon },
  ERDC: { facetKey: 'ERDC', desc: 'U.S. Army Engineer Research Center', icon: InstitutionIcon },
  GOTM: { facetKey: 'GOTM', desc: 'General Ocean Turbulence Model', icon: SoftwareIcon },
  PSU: { facetKey: 'PSU', desc: 'Penn State University', icon: InstitutionIcon },
  SWRI: { facetKey: 'SWRI', desc: 'Southwest Research Institute', icon: InstitutionIcon },
  eartH2Observe: { facetKey: 'eartH2Observe', desc: 'Global Hydrological Data', icon: OceanIcon },
};
