import {
  AbstractIcon,
  BookChapterIcon,
  BookIcon,
  CatalogIcon,
  CircularIcon,
  DatasetIcon,
  EditorialIcon,
  EPrintIcon,
  InstrumentIcon,
  JournalArticleIcon,
  MastersThesisIcon,
  NewsletterIcon,
  OtherIcon,
  PhdThesisIcon,
  PressReleaseIcon,
  ProceedingsArticleIcon,
  ProceedingsIcon,
  ProposalIcon,
  ServiceIcon,
  SoftwareIcon,
  TalkIcon,
  TechReportIcon,
} from '../icons/browser/doctype';
import { IFacetDescription } from './types';

export const doctypeSearchParamsMap: Record<string, string[]> = {
  '1/Article/Journal Article': ['article'],
  '1/Article/Proceedings Article': ['inproceedings'],
  '1/Article/e-print': ['eprint'],
  '1/Article/Book Chapter': ['inbook'],
  '1/Non-Article/Abstract': ['abstract'],
  '1/Non-Article/Proposal': ['proposal'],
  '1/Non-Article/Tech Report': ['techreport'],
  '1/Non-Article/PhD Thesis': ['phdthesis'],
  '1/Non-Article/Other': ['misc', 'obituary', 'erratum', 'bookreview'],
  '1/Non-Article/Circular': ['circular'],
  '1/Non-Article/Proceedings': ['proceedings'],
  '1/Non-Article/Dataset': ['dataset'],
  '1/Non-Article/Book': ['book'],
  '1/Non-Article/Editorial': ['editorial'],
  '1/Non-Article/Software': ['software'],
  '1/Non-Article/Newsletter': ['newsletter'],
  '1/Non-Article/Masters Thesis': ['mastersthesis'],
  '1/Non-Article/Press Release': ['pressrelease'],
  '1/Non-Article/Catalog': ['catalog'],
  '1/Non-Article/Talk': ['talk'],
  '1/Non-Article/Service': ['service'],
  '1/Non-Article/Instrument': ['instrument'],
};

export const doctypeDescriptions: Record<string, IFacetDescription> = {
  '1/Article/Journal Article': { facetKey: '1/Article/Journal Article', desc: null, icon: JournalArticleIcon },
  '1/Article/Proceedings Article': {
    facetKey: '1/Article/Proceedings Article',
    desc: null,
    icon: ProceedingsArticleIcon,
  },
  '1/Article/e-print': { facetKey: '1/Article/e-print', desc: null, icon: EPrintIcon },
  '1/Article/Book Chapter': { facetKey: '1/Article/Book Chapter', desc: null, icon: BookChapterIcon },
  '1/Non-Article/Abstract': { facetKey: '1/Non-Article/Abstract', desc: null, icon: AbstractIcon },
  '1/Non-Article/Proposal': { facetKey: '1/Non-Article/Proposal', desc: null, icon: ProposalIcon },
  '1/Non-Article/Tech Report': { facetKey: '1/Non-Article/Tech Report', desc: null, icon: TechReportIcon },
  '1/Non-Article/PhD Thesis': { facetKey: '1/Non-Article/PhD Thesis', desc: null, icon: PhdThesisIcon },
  '1/Non-Article/Other': { facetKey: '1/Non-Article/Other', desc: null, icon: OtherIcon },
  '1/Non-Article/Circular': { facetKey: '1/Non-Article/Circular', desc: null, icon: CircularIcon },
  '1/Non-Article/Proceedings': { facetKey: '1/Non-Article/Proceedings', desc: null, icon: ProceedingsIcon },
  '1/Non-Article/Dataset': { facetKey: '1/Non-Article/Dataset', desc: null, icon: DatasetIcon },
  '1/Non-Article/Book': { facetKey: '1/Non-Article/Book', desc: null, icon: BookIcon },
  '1/Non-Article/Editorial': { facetKey: '1/Non-Article/Editorial', desc: null, icon: EditorialIcon },
  '1/Non-Article/Software': { facetKey: '1/Non-Article/Software', desc: null, icon: SoftwareIcon },
  '1/Non-Article/Newsletter': { facetKey: '1/Non-Article/Newsletter', desc: null, icon: NewsletterIcon },
  '1/Non-Article/Masters Thesis': { facetKey: '1/Non-Article/Masters Thesis', desc: null, icon: MastersThesisIcon },
  '1/Non-Article/Press Release': { facetKey: '1/Non-Article/Press Release', desc: null, icon: PressReleaseIcon },
  '1/Non-Article/Catalog': { facetKey: '1/Non-Article/Catalog', desc: null, icon: CatalogIcon },
  '1/Non-Article/Talk': { facetKey: '1/Non-Article/Talk', desc: null, icon: TalkIcon },
  '1/Non-Article/Service': { facetKey: '1/Non-Article/Service', desc: null, icon: ServiceIcon },
  '1/Non-Article/Instrument': { facetKey: '1/Non-Article/Instrument', desc: null, icon: InstrumentIcon },
};
