import { ExportFormatsApiResponse } from '@/api/export/types';

export const DEFAULT_EXPORT_FORMATS: ExportFormatsApiResponse = [
  { name: 'BibTeX', type: 'tagged', route: '/bibtex', extension: 'bib' },
  { name: 'BibTeX ABS', type: 'tagged', route: '/bibtexabs', extension: 'bib' },
  { name: 'ADS', type: 'tagged', route: '/ads', extension: 'txt' },
  { name: 'EndNote', type: 'tagged', route: '/endnote', extension: 'enw' },
  { name: 'ProCite', type: 'tagged', route: '/procite', extension: 'txt' },
  { name: 'RIS', type: 'tagged', route: '/ris', extension: 'txt' },
  { name: 'RefWorks', type: 'tagged', route: '/refworks', extension: 'txt' },
  { name: 'MEDLARS', type: 'tagged', route: '/medlars', extension: 'txt' },
  { name: 'DC-XML', type: 'XML', route: '/dcxml', extension: 'xml' },
  { name: 'REF-XML', type: 'XML', route: '/refxml', extension: 'xml' },
  { name: 'REFABS-XML', type: 'XML', route: '/refabsxml', extension: 'xml' },
  { name: 'JATS-XML', type: 'XML', route: '/jatsxml', extension: 'xml' },
  { name: 'AASTeX', type: 'LaTeX', route: '/aastex', extension: 'txt' },
  { name: 'AASTeX (PSJ)', type: 'LaTeX', route: '/aastex-psj', extension: 'txt' },
  { name: 'Icarus', type: 'LaTeX', route: '/icarus', extension: 'txt' },
  { name: 'MNRAS', type: 'LaTeX', route: '/mnras', extension: 'txt' },
  { name: 'Solar Physics', type: 'LaTeX', route: '/soph', extension: 'txt' },
  { name: 'ASP Conference', type: 'LaTeX', route: '/aspc', extension: 'txt' },
  { name: 'AAS Journals', type: 'LaTeX', route: '/aasj', extension: 'txt' },
  { name: 'APS Journals', type: 'HTML', route: '/apsj', extension: 'rtf' },
  { name: 'IEEE', type: 'HTML', route: '/ieee', extension: 'rtf' },
  { name: 'AGU', type: 'HTML', route: '/agu', extension: 'rtf' },
  { name: 'GSA', type: 'HTML', route: '/gsa', extension: 'rtf' },
  { name: 'AMS (Meteorological)', type: 'HTML', route: '/ams', extension: 'rtf' },
  { name: 'CSL', type: 'custom', route: '/csl', extension: 'txt' },
  { name: 'custom', type: 'custom', route: '/custom', extension: 'txt' },
  { name: 'VOTable', type: 'XML', route: '/votable', extension: 'xml' },
  { name: 'RSS', type: 'XML', route: '/rss', extension: 'rss' },
];
