import { ExportFormatsApiResponse } from '@/api/export/types';

export const DEFAULT_EXPORT_FORMATS: ExportFormatsApiResponse = [
  { name: 'BibTeX', type: 'tagged', route: '/bibtex' },
  { name: 'BibTeX ABS', type: 'tagged', route: '/bibtexabs' },
  { name: 'ADS', type: 'tagged', route: '/ads' },
  { name: 'EndNote', type: 'tagged', route: '/endnote' },
  { name: 'ProCite', type: 'tagged', route: '/procite' },
  { name: 'RIS', type: 'tagged', route: '/ris' },
  { name: 'RefWorks', type: 'tagged', route: '/refworks' },
  { name: 'MEDLARS', type: 'tagged', route: '/medlars' },
  { name: 'DC-XML', type: 'XML', route: '/dcxml' },
  { name: 'REF-XML', type: 'XML', route: '/refxml' },
  { name: 'REFABS-XML', type: 'XML', route: '/refabsxml' },
  { name: 'JATS-XML', type: 'XML', route: '/jatsxml' },
  { name: 'AASTeX', type: 'LaTeX', route: '/aastex' },
  { name: 'AASTeX (PSJ)', type: 'LaTeX', route: '/aastex-psj' },
  { name: 'Icarus', type: 'LaTeX', route: '/icarus' },
  { name: 'MNRAS', type: 'LaTeX', route: '/mnras' },
  { name: 'Solar Physics', type: 'LaTeX', route: '/soph' },
  { name: 'ASPC', type: 'LaTeX', route: '/aspc' },
  { name: 'ASP Conference', type: 'LaTeX', route: '/aspc/<bibcode>' },
  { name: 'AAS Journals', type: 'LaTeX', route: '/aasj' },
  { name: 'APS Journals', type: 'text', route: '/apsj' },
  { name: 'IEEE', type: 'text', route: '/ieee' },
  { name: 'AGU', type: 'text', route: '/agu' },
  { name: 'GSA', type: 'text', route: '/gsa' },
  { name: 'AMS (Meteorological)', type: 'text', route: '/ams' },
  { name: 'CSL', type: 'custom', route: '/csl' },
  { name: 'custom', type: 'custom', route: '/custom' },
  { name: 'VOTable', type: 'XML', route: '/votable' },
  { name: 'RSS', type: 'XML', route: '/rss' },
];
