version: '3.8'

services:
  app:
    ports:
      - '8000:8000'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 12
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      DOPPLER_TOKEN: dp.st.dev.NYcb6F2CIFTB51PHLtRfm1o9lUnycJ3FYfskJ7S6
