import { TypeaheadOption } from './types';

export const typeaheadOptions: TypeaheadOption[] = [
  { value: 'author:""', label: 'Author', match: ['author:"'], desc: '', id: 0 },
  { value: 'first_author:""', label: 'First Author', match: ['first author', 'first_author:"'], desc: '', id: 1 },
  { value: 'bibcode:""', label: 'Bibcode', desc: 'e.g. bibcode:1989ApJ...342L..71R', match: ['bibcode:"'], id: 2 },
  {
    value: 'bibstem:""',
    label: 'Publication',
    desc: 'e.g. bibstem:ApJ',
    match: ['bibstem:"', 'publication (bibstem)'],
    id: 3,
  },
  { value: 'arXiv:', label: 'arXiv ID', desc: '', match: ['arxiv:'], id: 4 },
  { value: 'doi:', label: 'DOI', desc: '', match: ['doi:'], id: 5 },
  {
    value: 'full:""',
    label: 'Full text search',
    desc: 'title, abstract, and body',
    match: ['full:', 'fulltext'],
    id: 6,
  },
  { value: 'full:""', label: 'Full text search', desc: 'title, abstract, and body', match: ['text'], id: 7 },
  { value: 'year:', label: 'Year', match: ['year'], desc: '', id: 8 },
  { value: 'year:1999-2005', label: 'Year Range', desc: 'e.g. 1999-2005', match: ['year', 'range'], id: 9 },
  { value: 'aff:""', label: 'Affiliation', match: ['aff:'], desc: '', id: 10 },
  { value: 'abs:""', label: 'Search abstract + title + keywords', match: ['abs:'], desc: '', id: 11 },
  {
    value: 'collection:astronomy',
    label: 'Limit to papers in the astronomy collection',
    match: ['astronomy', 'collection:astronomy'],
    desc: '',
    id: 12,
  },
  {
    value: 'collection:physics',
    label: 'Limit to papers in the physics collection',
    match: ['physics', 'collection:physics'],
    desc: '',
    id: 13,
  },
  { value: 'title:""', label: 'Title', match: ['title:"'], desc: '', id: 14 },
  { value: 'orcid:', label: 'ORCiD identifier', match: ['orcid:'], desc: '', id: 15 },
  { value: 'object:', label: 'SIMBAD object (e.g. object:LMC)', desc: '', match: ['object:'], id: 16 },
  {
    value: 'property:refereed',
    label: 'Limit to refereed',
    desc: '(property:refereed)',
    match: ['refereed', 'property:refereed'],
    id: 17,
  },
  {
    value: 'property:notrefereed',
    label: 'Limit to non-refereed',
    desc: '(property:notrefereed)',
    match: ['notrefereed', 'property:notrefereed'],
    id: 18,
  },
  {
    value: 'property:eprint',
    label: 'Limit to eprints',
    desc: '(property:eprint)',
    match: ['eprint', 'property:eprint'],
    id: 19,
  },
  {
    value: 'property:openaccess',
    label: 'Limit to open access',
    desc: '(property:openaccess)',
    match: ['property:openaccess', 'openaccess'],
    id: 20,
  },
  {
    value: 'doctype:software',
    label: 'Limit to software',
    desc: '(doctype:software)',
    match: ['software', 'doctype:software'],
    id: 21,
  },
  {
    value: 'property:inproceedings',
    label: 'Limit to papers in conference proceedings',
    desc: '(property:inproceedings)',
    match: ['proceedings', 'property:inproceedings'],
    id: 22,
  },
  {
    value: 'citations()',
    label: 'Citations',
    desc: 'Get papers citing your search result set',
    match: ['citations('],
    id: 23,
  },
  {
    value: 'references()',
    label: 'References',
    desc: 'Get papers referenced by your search result set',
    match: ['references('],
    id: 24,
  },
  {
    value: 'trending()',
    label: 'Trending',
    desc: 'Get papers most read by users who recently read your search result set',
    match: ['trending('],
    id: 25,
  },
  {
    value: 'reviews()',
    label: 'Review Articles',
    desc: 'Get most relevant papers that cite your search result set',
    match: ['reviews('],
    id: 26,
  },
  {
    value: 'useful()',
    label: 'Useful',
    desc: 'Get papers most frequently cited by your search result set',
    match: ['useful('],
    id: 27,
  },
  {
    value: 'similar()',
    label: 'Similar',
    desc: 'Get papers that have similar full text to your search result set',
    match: ['similar('],
    id: 28,
  },
  {
    value: 'collection:earthscience',
    label: 'Limit to papers in the earth science collection',
    match: ['earth science', 'collection:earthscience'],
    desc: '',
    id: 29,
  },
];

export type SearchTermItem = {
  type: 'item';
  title: string;
  id: string;
  value: string;
  description: string;
  syntax: string[];
  example: string[];
};
export type SearchTermGroup = {
  type: 'group';
  title: string;
};

export type SearchTermOption = SearchTermItem | SearchTermGroup;

export const allSearchTerms: SearchTermOption[] = [
  // Fields
  {
    type: 'group',
    title: 'fields',
  },
  {
    type: 'item',
    id: 'abs',
    value: 'abs:""',
    title: 'abstract',
    description: 'Search for word or phrase in abstract, title and keywords',
    syntax: ['abs:"phrase"'],
    example: ['abs:"dark energy"'],
  },
  {
    type: 'item',
    id: 'abstract',
    value: 'abstract:""',
    title: 'abstract only',
    description: 'Search for a word or phrase in an abstract only',
    syntax: ['abstract:"phrase"'],
    example: ['abstract:"dark energy"'],
  },
  {
    type: 'item',
    id: 'ack',
    value: 'ack:""',
    title: 'acknowledgements',
    description: 'Search for a word or phrase in the acknowledgements extracted from fulltexts.',
    syntax: ['ack:"phrase"'],
    example: ['ack:"ADS"'],
  },
  {
    type: 'item',
    id: 'aff',
    value: 'aff:""',
    title: 'affiliation',
    description: 'Search for word or phrase in the raw, provided affiliation field',
    syntax: ['aff:"phrase"'],
    example: ['aff:"harvard"'],
  },
  {
    type: 'item',
    id: 'arxiv_class',
    value: 'arxiv_class:""',
    title: 'arXiv category',
    description: 'Finds all arXiv pre-prints in the class specified',
    syntax: ['arxiv_class:"arxivclass"'],
    example: ['arxiv_class:"High Energy Physics - Experiment"'],
  },
  {
    type: 'item',
    id: 'author_count',
    value: 'author_count:[1 TO 20]',
    title: 'author count',
    description: 'Find records that have a specific number of authors, or a range of author counts',
    syntax: ['author_count:count', 'author_count:[min_count TO max_count]'],
    example: ['author_count:40', 'author_count:[10 TO 100]'],
  },
  {
    type: 'item',
    id: 'author',
    value: 'author:""',
    title: 'author',
    description: 'Author name may include just lastname and initial, or stricter author search (recommended)',
    syntax: ['author:"Last, F"', 'author:"Last, First M"'],
    example: ['author:"huchra, john p"'],
  },
  {
    type: 'item',
    id: 'bibcode',
    value: 'bibcode:',
    title: 'bibcode',
    description: 'Find a specific record using the ADS bibcode (ADS identifier of a paper)',
    syntax: ['bibcode:adsbib'],
    example: ['bibcode:2003AJ….125..525J'],
  },
  {
    type: 'item',
    id: 'bibgroup',
    value: 'bibgroup:',
    title: 'bibliographic group',
    description: 'Limit search to papers in HST bibliography',
    syntax: ['bibgroup:name'],
    example: ['bibgroup:HST'],
  },
  {
    type: 'item',
    id: 'bibstem',
    value: 'bibstem:',
    title: 'bib abbrev',
    description:
      'Find records that contain a specific bibstem in their bibcode. A full list is available <a href="/journalsdb" ref="noopener noreferrer" target="_blank">here</a>.',
    syntax: ['bibstem:adsbibstem'],
    example: ['bibstem:ApJ'],
  },
  {
    type: 'item',
    id: 'body',
    value: 'body:""',
    title: 'body of article',
    description: 'Search for a word or phrase in (only) the full text',
    syntax: ['body:"phrase"'],
    example: ['body:"gravitational waves"'],
  },
  {
    type: 'item',
    id: 'data',
    value: 'data:',
    title: 'data archive',
    description: 'Limit search to papers with data from specified',
    syntax: ['data:archive'],
    example: ['data:NED'],
  },
  {
    type: 'item',
    id: 'collection',
    value: 'collection:',
    title: 'collection',
    description: 'Search from the astronomy, physics, earth science, or general collection',
    syntax: ['collection:collection'],
    example: ['collection:general'],
  },
  {
    type: 'item',
    id: 'citation_count',
    value: 'citation_count:',
    title: 'citation count',
    description: 'Find records that have a specific number of citations, or a range of citation counts',
    syntax: ['citation_count:count', 'citation_count:[min_count TO max_count]'],
    example: ['citation_count:40', 'citation_count:[10 TO 100]'],
  },
  {
    type: 'item',
    id: 'doctype',
    value: 'doctype:',
    title: 'doctype',
    description: 'Limit search to records corresponding to data catalogs',
    syntax: ['doctype:type'],
    example: ['doctype:catalog'],
  },
  {
    type: 'item',
    id: 'doi',
    value: 'doi:',
    title: 'doi',
    description: 'finds a specific record using its digital object id',
    syntax: ['doi:DOI'],
    example: ['doi:10.1086/345794'],
  },
  {
    type: 'item',
    id: 'entdate',
    value: 'entdate:',
    title: 'entdate',
    description: 'Creation date of ADS record in user-friendly format (YYYY-MM-DD)',
    syntax: ['entdate:YYYY-MM-DD'],
    example: ['entdate:2019-05-20'],
  },
  {
    type: 'item',
    id: 'first-author',
    value: 'first_author:""',
    title: 'first author',
    description: 'Search by first author of the paper',
    syntax: ['first_author:"Last, F"'],
    example: ['first_author:"huchra, j"'],
  },
  {
    type: 'item',
    id: 'full',
    value: 'full:""',
    title: 'fulltext',
    description: 'Search for word or phrase in fulltext, acknowledgements, abstract, title and keywords',
    syntax: ['full:"phrase"'],
    example: ['full:"gravitational waves"'],
  },
  {
    type: 'item',
    id: 'identifier',
    value: 'identifier:',
    title: 'identifier',
    description: 'Find a paper using any of its identifiers, arXiv, bibcode, doi, etc.',
    syntax: ['identifier:bibcode'],
    example: ['identifier:2003AJ….125..525J'],
  },
  {
    type: 'item',
    id: 'inst',
    value: 'inst:',
    title: 'institution',
    description:
      'Search by author\'s canonical affiliation. Click <a href="https://github.com/adsabs/CanonicalAffiliations/blob/master/parent_child.tsv" ref="noopener noreferrer" target="_blank">here</a> for a full list',
    syntax: ['inst:id'],
    example: ['inst:CfA'],
  },
  {
    type: 'item',
    id: 'keyword',
    value: 'keyword:""',
    title: 'keyword',
    description: 'Search publisher- or author-supplied keywords',
    syntax: ['keyword:"phrase"'],
    example: ['keyword:sun'],
  },
  {
    type: 'item',
    id: 'object',
    value: 'object:',
    title: 'object',
    description: 'Search for papers tagged with a specific astronomical object or at or near a set of coordinates',
    syntax: ['object:"object"'],
    example: ['object:Andromeda'],
  },
  {
    type: 'item',
    id: 'orcid',
    value: 'orcid:',
    title: 'orcid',
    description: 'Search for papers that are associated with a specific ORCiD iD',
    syntax: ['orcid:id'],
    example: ['orcid:0000-0000-0000-0000'],
  },
  {
    type: 'item',
    id: 'page',
    value: 'page:',
    title: 'page',
    description: 'Search for papers with a given page number',
    syntax: ['page:number'],
    example: ['page:410'],
  },
  {
    type: 'item',
    id: 'property',
    value: 'property:',
    title: 'property',
    description:
      'An array of miscellaneous flags associated with the record. Possible values include: refereed, notrefereed, article, nonarticle, ads_openaccess, eprint_openaccess, pub_openaccess, openaccess, ocrabstract',
    syntax: ['property:type'],
    example: ['property:openaccess'],
  },
  {
    type: 'item',
    id: 'pub',
    value: 'bibstem:',
    title: 'publication full name',
    description:
      'Limit search to a specific publication. A full list is available <a href="/journalsdb" ref="noopener noreferrer" target="_blank">here</a>.',
    syntax: ['pub:adsbibstem'],
    example: ['pub:ApJ'],
  },
  {
    type: 'item',
    id: 'pubdate',
    value: 'pubdate:',
    title: 'date published',
    description: 'Use fine-grained dates for publication range',
    syntax: ['pubdate:[YYYY-MM TO YYYY-MM]'],
    example: ['pubdate:[2005-10 TO 2006-09]'],
  },
  {
    type: 'item',
    id: 'title',
    value: 'title:""',
    title: 'title',
    description: 'Search for word or phrase in title field',
    syntax: ['title:"phrase"'],
    example: ['title:"weak lensing"'],
  },
  {
    type: 'item',
    id: 'volume',
    value: 'volume:',
    title: 'volume',
    description: 'Search for papers with a given volume',
    syntax: ['volume:volume'],
    example: ['volume:10'],
  },
  {
    type: 'item',
    id: 'year',
    value: 'year:',
    title: 'year',
    description: 'Year of publication',
    syntax: ['year:YYYY', 'year:YYYY-YYYY'],
    example: ['year:2000', 'year:2000-2005'],
  },

  // Operators
  {
    type: 'group',
    title: 'operators',
  },
  {
    type: 'item',
    id: 'citations',
    value: 'citations()',
    title: 'citations()',
    description: 'Returns list of citations from given papers; use [citations] to get the field contents',
    syntax: ['citations(query)'],
    example: ['citations(author:"huchra, john")'],
  },
  {
    type: 'item',
    id: 'pos',
    value: 'pos()',
    title: 'pos()',
    description:
      'Search for an item within a field by specifying the position in the field. The example for this operator is pos(fieldedquery,position,[endposition]). If no endposition is given, then it is assumed to be endposition = position, otherwise this performs a query within the range [position, endposition].',
    syntax: ['pos(fieldedquery,position,[endposition])'],
    example: ['pos(author:"Oort, J",2)'],
  },
  {
    type: 'item',
    id: 'references',
    value: 'references()',
    title: 'references()',
    description: 'Returns list of references from given papers',
    syntax: ['references(query)'],
    example: ['references(bibcode:2003AJ....125..525J)'],
  },
  {
    type: 'item',
    id: 'reviews',
    value: 'reviews()',
    title: 'reviews()',
    description:
      'Returns the list of documents citing the most relevant papers on the topic being researched; these are papers containing the most extensive reviews of the field.',
    syntax: ['reviews(query)'],
    example: ['reviews("weak lensing")'],
  },
  {
    type: 'item',
    id: 'similar',
    value: 'similar()',
    title: 'similar()',
    description: 'Return similar documents, based on the similarity of the abstract text',
    syntax: ['similar(query)'],
    example: ['similar(bibcode:2000A&AS..143...41K)'],
  },
  {
    type: 'item',
    id: 'topn',
    value: 'topn()',
    title: 'topn()',
    description: 'Return the top N number of documents',
    syntax: ['topn(N, query)'],
    example: ['topn(100, database:astronomy, citation_count desc)'],
  },
  {
    type: 'item',
    id: 'trending',
    value: 'trending()',
    title: 'trending()',
    description:
      'Returns the list of documents most read by users who read recent papers on the topic being researched; these are papers currently being read by people interested in this field.',
    syntax: ['trending(query)'],
    example: ['trending(exoplanets)'],
  },
  {
    type: 'item',
    id: 'useful',
    value: 'useful()',
    title: 'useful()',
    description:
      'Returns the list of documents frequently cited by the most relevant papers on the topic being researched; these are studies which discuss methods and techniques useful to conduct research in this field.',
    syntax: ['useful(query)'],
    example: ['useful("galaxy surveys")'],
  },

  // Special Characters
  {
    type: 'group',
    title: 'special characters',
  },
  {
    type: 'item',
    id: '?',
    value: '""?',
    title: 'single wildcard: ?',
    description: 'Matches a single character',
    syntax: ['?'],
    example: ['title:(k? star)'],
  },
  {
    type: 'item',
    id: '*',
    value: '""*',
    title: 'wildcard: *',
    description: 'Matches zero or more sequential characters',
    syntax: ['*'],
    example: ['title:(gravit* wave)'],
  },
  {
    type: 'item',
    id: '=',
    value: '=""',
    title: 'exact match: =',
    description: 'Exact match',
    syntax: ['=query'],
    example: ['=author:"murray, stephen"'],
  },
];

export const quickfields: SearchTermItem[] = [
  {
    type: 'item',
    id: 'author',
    value: 'author:""',
    title: 'author',
    description: 'Author name may include just lastname and initial, or stricter author search (recommended)',
    syntax: ['author:"Last, F"', 'author:"Last, First M"'],
    example: ['author:"huchra, john p"'],
  },

  {
    type: 'item',
    id: 'first-author',
    value: 'first_author:""',
    title: 'first author',
    description: 'Search by first author of the paper',
    syntax: ['first_author:"Last, F"'],
    example: ['first_author:"huchra, j"'],
  },
  {
    type: 'item',
    id: 'abs',
    value: 'abs:""',
    title: 'abstract',
    description: 'Search for word or phrase in abstract, title and keywords',
    syntax: ['abs:"phrase"'],
    example: ['abs:"dark energy"'],
  },
  {
    type: 'item',
    id: 'year',
    value: 'year:',
    title: 'year',
    description: 'Year of publication',
    syntax: ['year:YYYY', 'year:YYYY-YYYY'],
    example: ['year:2000', 'year:2000-2005'],
  },
  {
    type: 'item',
    id: 'full',
    value: 'full:""',
    title: 'fulltext',
    description: 'Search for word or phrase in fulltext, acknowledgements, abstract, title and keywords',
    syntax: ['full:"phrase"'],
    example: ['full:"gravitational waves"'],
  },
];
