name: CI
on: [push, pull_request]
jobs:
  build:
    name: Install deps, build project on Node.js
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18 ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      # Run linter
      - name: Lint
        run: pnpm lint

      # Run tests (with coverage)
      - name: Test
        run: pnpm test:coverage

      # Upload code coverage report
      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-nectar
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true

      # Build
      - name: Build
        if: always()
        run: pnpm build
