name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build, lint, and test on Node
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18 ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      # Install Deps
      - name: Install dependencies
        run: pnpm install

      # Run linter
      - name: Lint
        run: pnpm lint

      # Run tests (with coverage)
      - name: Test
        run: pnpm test:coverage

      # Upload code coverage report
      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-nectar
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true

      # Build project
      - name: Build
        if: always()
        run: pnpm build
