name: Pull Request

on: [push, pull_request]

jobs:
  build-and-lint:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false
      - uses: actions/cache@v3
        name: restore/setup pnpm cache
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 SENTRYCLI_SKIP_DOWNLOAD=1 pnpm install

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

  unit-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false
      - uses: actions/cache@v3
        name: restore/setup pnpm cache
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 SENTRYCLI_SKIP_DOWNLOAD=1 pnpm install

      - name: Test
        run: pnpm test:coverage

      - name: Upload Coverage
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          fail_ci_if_error: false
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-nectar
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true

  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      CI: true
      BASE_CANONICAL_URL: ${{ vars.BASE_CANONICAL_URL }}
      API_HOST_CLIENT: ${{ vars.API_HOST_CLIENT }}
      API_HOST_SERVER: ${{ vars.API_HOST_SERVER }}
      COOKIE_SECRET: ${{ vars.COOKIE_SECRET }}
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false
      - uses: actions/cache@v3
        name: restore/setup pnpm cache
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: setup environment variables
        run: |
          touch .env.local
          echo "CI=${{ env.CI }}" >> .env.local
          echo "BASE_CANONICAL_URL=${{ env.BASE_CANONICAL_URL }}" >> .env.local
          echo "API_HOST_CLIENT=${{ env.API_HOST_CLIENT }}" >> .env.local
          echo "API_HOST_SERVER=${{ env.API_HOST_SERVER }}" >> .env.local
          echo "COOKIE_SECRET=${{ env.COOKIE_SECRET }}" >> .env.local

      - name: Run integration tests
        run: pnpm integration

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
