name: End-to-end

on: [push, pull_request]

env:
  BASE_CANONICAL_URL: ${{ vars.BASE_CANONICAL_URL }}
  API_HOST_CLIENT: ${{ vars.API_HOST_CLIENT }}
  API_HOST_SERVER: ${{ vars.API_HOST_SERVER }}
  COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
  ADS_SESSION_COOKIE_NAME: ${{ vars.ADS_SESSION_COOKIE_NAME }}
  SCIX_SESSION_COOKIE_NAME: ${{ vars.SCIX_SESSION_COOKIE_NAME }}

jobs:
  unit-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18 ]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false
      - uses: actions/cache@v3
        name: restore/setup pnpm cache
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test:coverage

      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-nectar
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true

  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18 ]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false
      - uses: actions/cache@v3
        name: restore/setup pnpm cache
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run integration tests
        run: pnpm integration

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
